// MapleCheck ownership database
//
// Built from public sources per RESEARCH-PROCESS.md: exchange listings and
// filings first, then acquisition records for private companies, with the
// sources named in each entry's note field.
//
// STATUS: every entry previously flagged for review has now been through a
// dedicated verification pass. What that pass could resolve, it resolved
// (Hudson's Bay, Mackage, AutoTrader, The Body Shop, TikTok). What remains
// flagged is flagged because the ownership genuinely has no single answer,
// or because a real-world process has not finished yet — not because the
// checking is outstanding.
//
// The entries never flagged have NOT each been individually re-sourced.
// They rest on uncontested public facts (stock listings, headquarters,
// well-documented acquisitions), which is a reasonable basis for what this
// extension claims, but it is not the same as a per-entry legal review.
//
// confidence: "high"   = uncontested public fact, source named in the note
// confidence: "verify" = shown to users as "still being verified", for one
//                        of two reasons the note always spells out:
//                          (a) genuinely mixed ownership with no single
//                              national answer (Tim Hortons, Lululemon,
//                              Molson Coors, Nuvei), or
//                          (b) an unfinished real-world process — an
//                              insolvency or an expiring licence (the Spark
//                              Networks brands, Toys "R" Us Canada)
//
// ownership: "verify" is separate from confidence — it means no flag is
// assigned at all, for companies where picking one country would misinform.

const OWNERSHIP_DATA = {
  // ---- US-owned / US-headquartered ----
  "walmart.ca": { brand: "Walmart", ownership: "US", category: "Retail & Department Stores", hq: "Bentonville, Arkansas", note: "NYSE: WMT", confidence: "high",
    alternatives: ["Loblaws / Real Canadian Superstore", "Sobeys", "Giant Tiger"] },
  "amazon.ca": { brand: "Amazon", ownership: "US", category: "Tech & Online Services", hq: "Seattle, Washington", note: "NASDAQ: AMZN", confidence: "high",
    alternatives: ["Well.ca", "Indigo.ca", "local retailers"] },
  "costco.ca": { brand: "Costco", ownership: "US", category: "Retail & Department Stores", hq: "Issaquah, Washington", note: "NASDAQ: COST", confidence: "high",
    alternatives: ["Wholesale Club (Federated Co-op)", "Loblaws"] },
  "homedepot.ca": { brand: "Home Depot", ownership: "US", category: "Home & Furniture", hq: "Atlanta, Georgia", note: "NYSE: HD", confidence: "high",
    alternatives: ["Canadian Tire", "Home Hardware"] },
  "target.com": { brand: "Target", ownership: "US", category: "Retail & Department Stores", hq: "Minneapolis, Minnesota", note: "NYSE: TGT — no longer operates stores in Canada but ships to CA", confidence: "high",
    alternatives: ["Canadian Tire", "Winners"] },
  "bestbuy.ca": { brand: "Best Buy", ownership: "US", category: "Retail & Department Stores", hq: "Richfield, Minnesota", note: "NYSE: BBY", confidence: "high",
    alternatives: ["Canada Computers", "Memory Express"] },
  "starbucks.ca": { brand: "Starbucks", ownership: "US", category: "Food & Drink", hq: "Seattle, Washington", note: "NASDAQ: SBUX", confidence: "high",
    alternatives: ["Second Cup (Canadian, Foodtastic-owned)", "local roasters"] },
  "mcdonalds.com": { brand: "McDonald's", ownership: "US", category: "Food & Drink", hq: "Chicago, Illinois", note: "NYSE: MCD", confidence: "high",
    alternatives: ["A&W Canada (Canadian-owned since 1972, separate from the US chain)", "Harvey's (Recipe Unlimited, Canadian)"] },
  "netflix.com": { brand: "Netflix", ownership: "US", category: "Media & Entertainment", hq: "Los Gatos, California", note: "NASDAQ: NFLX", confidence: "high",
    alternatives: ["CBC Gem", "Crave"] },
  "rona.ca": { brand: "Rona", ownership: "US", category: "Home & Furniture", hq: "Boucherville, QC (operations) — owned by Sycamore Partners, New York", note: "Sold by Lowe's to US private equity firm Sycamore Partners in Feb 2023. Despite Canadian branding/history and 'Truly Canadian' marketing, current ownership is US private equity. Source: Lowe's/Sycamore Partners deal announcements, Nov 2022–Feb 2023.", confidence: "high",
    alternatives: ["Canadian Tire", "Home Hardware"] },
  "staples.ca": { brand: "Staples Canada", ownership: "US", category: "Retail & Department Stores", hq: "Richmond Hill, ON (operations) — owned by Sycamore Partners, New York", note: "Same US private equity owner as Rona (Sycamore Partners)", confidence: "high",
    alternatives: ["Grand & Toy", "local office suppliers"] },
  "apple.com": { brand: "Apple", ownership: "US", category: "Tech & Online Services", hq: "Cupertino, California", note: "NASDAQ: AAPL", confidence: "high",
    alternatives: [], otherAlternatives: ["Samsung (South Korea)"], alternativesNote: "No Canadian phone/OS maker exists. Samsung isn't Canadian either, but it's not US-owned — listed as a non-US option, not a Canadian one." },
  "google.com": { brand: "Google", ownership: "US", category: "Tech & Online Services", hq: "Mountain View, California", note: "NASDAQ: GOOGL (Alphabet)", confidence: "high",
    alternatives: [], otherAlternatives: ["Ecosia (Germany)", "Qwant (France)"], alternativesNote: "No Canadian search engine at scale. DuckDuckGo is often suggested but is also US-owned (Pennsylvania) — excluded for that reason. Ecosia/Qwant are non-US, not Canadian." },
  "microsoft.com": { brand: "Microsoft", ownership: "US", category: "Tech & Online Services", hq: "Redmond, Washington", note: "NASDAQ: MSFT", confidence: "high",
    alternatives: [], otherAlternatives: ["LibreOffice (open-source, EU-based nonprofit)"], alternativesNote: "No Canadian OS/productivity suite at scale. LibreOffice isn't Canadian but isn't a US corporation either." },
  "uber.com": { brand: "Uber", ownership: "US", category: "Travel & Transportation", hq: "San Francisco, California", note: "NYSE: UBER", confidence: "high",
    alternatives: ["local taxi apps"] },
  "winners.ca": { brand: "Winners / Marshalls / HomeSense", ownership: "US", category: "Retail & Department Stores", hq: "Framingham, Massachusetts", note: "Owned by TJX Companies, NYSE: TJX", confidence: "high",
    alternatives: [] },
  "ikea.com": { brand: "IKEA", ownership: "not-US", category: "Home & Furniture", hq: "Leiden, Netherlands (Inter IKEA) / founded Sweden", note: "Not US-owned — the Inter IKEA/Netherlands foundation structure is well-documented, publicly established fact, not a disputed or unclear case. Not Canadian either.", confidence: "high",
    alternatives: [] },

  // ---- Canadian-owned ----
  "loblaws.ca": { brand: "Loblaws", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Brampton, Ontario", note: "Owned by George Weston Limited / Weston family, TSX: L", confidence: "high",
    alternatives: [] },
  "canadiantire.ca": { brand: "Canadian Tire", ownership: "Canada", category: "Retail & Department Stores", hq: "Toronto, Ontario", note: "TSX: CTC", confidence: "high",
    alternatives: [] },
  "timhortons.ca": { brand: "Tim Hortons", ownership: "verify", category: "Food & Drink", hq: "Toronto, Ontario (RBI) / Oakville, Ontario (brand)", note: "Checked, and there is no single right answer — this flag is the finding, not an unfinished task. Tim Hortons is run as a Canadian business with a Canadian brand HQ, but the parent is Restaurant Brands International, which also owns Burger King and Popeyes, is dual-listed on the NYSE and TSX, and keeps its head office in Toronto. RBI was created by the 2014 merger backed by Brazil's 3G Capital, whose stake has fallen from roughly 51% to about 26%, while Canadian institutions (TD, BMO, RBC, CPP Investment Board) now hold a comparable combined position. No one country controls it, so MapleCheck does not assign a flag.", confidence: "verify",
    alternatives: [] },
  "sobeys.com": { brand: "Sobeys", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Stellarton, Nova Scotia", note: "Owned by Empire Company Ltd., TSX: EMP.A", confidence: "high",
    alternatives: [] },
  "mec.ca": { brand: "Mountain Equipment Company (MEC)", ownership: "Canada", category: "Apparel & Fashion", hq: "Vancouver, BC", note: "Sold back to a Canadian investor group led by Tim Gu (also an investor in Roots and Tilley) in May 2025, ending the 2020–2025 period of US private equity ownership under Kingswood Capital Management. Confirmed via MEC's own press release plus independent retail trade reporting (retail-insider.com, hardlines.ca). A partial management buyout — CEO Peter Hlynsky and CMO Chris Speyer are also part of the new ownership group.", confidence: "high",
    alternatives: [] },
  "indigo.ca": { brand: "Indigo", ownership: "Canada", category: "Retail & Department Stores", hq: "Toronto, Ontario", note: "TSX: IDG", confidence: "high",
    alternatives: [] },
  "well.ca": { brand: "Well.ca", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Ontario", note: "Owned by Birch Hill Equity Partners (Canadian PE firm) since Dec 2024, after being owned by US-based McKesson 2016–2024. Source: McKesson divestiture announcement, Dec 30 2024.", confidence: "high",
    alternatives: [] },
  "rexall.ca": { brand: "Rexall", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Mississauga, Ontario", note: "Owned by Birch Hill Equity Partners (Canadian PE firm) since Dec 2024, after being owned by US-based McKesson 2016–2024. Same ownership history as Well.ca.", confidence: "high",
    alternatives: [] },
  "bell.ca": { brand: "Bell Canada", ownership: "Canada", category: "Telecom & Mobile", hq: "Verdun, Quebec", note: "Owned by BCE Inc., TSX: BCE", confidence: "high",
    alternatives: [] },
  "rogers.com": { brand: "Rogers", ownership: "Canada", category: "Telecom & Mobile", hq: "Toronto, Ontario", note: "TSX: RCI.B — Rogers family control", confidence: "high",
    alternatives: [] },
  "telus.com": { brand: "Telus", ownership: "Canada", category: "Telecom & Mobile", hq: "Vancouver, BC", note: "TSX: T", confidence: "high",
    alternatives: [] },
  "rbc.com": { brand: "RBC (Royal Bank of Canada)", ownership: "Canada", category: "Banking & Insurance", hq: "Toronto, Ontario", note: "TSX: RY", confidence: "high",
    alternatives: [] },
  "td.com": { brand: "TD Bank", ownership: "Canada", category: "Banking & Insurance", hq: "Toronto, Ontario", note: "TSX: TD — note: TD also operates US retail banking (TD Bank, N.A.) as a subsidiary, but the parent company is Canadian", confidence: "high",
    alternatives: [] },
  "scotiabank.com": { brand: "Scotiabank", ownership: "Canada", category: "Banking & Insurance", hq: "Toronto, Ontario", note: "TSX: BNS", confidence: "high",
    alternatives: [] },
  "bmo.com": { brand: "BMO (Bank of Montreal)", ownership: "Canada", category: "Banking & Insurance", hq: "Montreal / Toronto", note: "TSX: BMO", confidence: "high",
    alternatives: [] },
  "cibc.com": { brand: "CIBC", ownership: "Canada", category: "Banking & Insurance", hq: "Toronto, Ontario", note: "TSX: CM", confidence: "high",
    alternatives: [] },
  "shoppersdrugmart.ca": { brand: "Shoppers Drug Mart", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Toronto, Ontario", note: "Owned by Loblaw Companies / George Weston Limited", confidence: "high",
    alternatives: [] },
  "metro.ca": { brand: "Metro", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Montreal, Quebec", note: "TSX: MRU", confidence: "high",
    alternatives: [] },
  "dollarama.com": { brand: "Dollarama", ownership: "Canada", category: "Retail & Department Stores", hq: "Montreal, Quebec", note: "TSX: DOL", confidence: "high",
    alternatives: [] },
  "shopify.com": { brand: "Shopify", ownership: "Canada", category: "Tech & Online Services", hq: "Ottawa, Ontario", note: "TSX/NYSE: SHOP — founded and headquartered in Canada", confidence: "high",
    alternatives: [] },
  "aircanada.com": { brand: "Air Canada", ownership: "Canada", category: "Travel & Transportation", hq: "Montreal, Quebec", note: "TSX: AC", confidence: "high",
    alternatives: [] },
  "westjet.com": { brand: "WestJet", ownership: "Canada", category: "Travel & Transportation", hq: "Calgary, Alberta", note: "Owned by Onex Corporation, a Canadian private equity firm, since 2019", confidence: "high",
    alternatives: [] },
  "homehardware.ca": { brand: "Home Hardware", ownership: "Canada", category: "Home & Furniture", hq: "St. Jacobs, Ontario", note: "Independently, privately Canadian-owned dealer cooperative", confidence: "high",
    alternatives: [] },
  "lululemon.com": { brand: "Lululemon", ownership: "verify", category: "Apparel & Fashion", hq: "Vancouver, British Columbia (headquarters) / Delaware, US (incorporation)", note: "Checked, and it stays split by design — this flag is the finding. Founded in Vancouver in 1998 and still headquartered there, with design and much of its senior team in BC, but the company is incorporated in Delaware and listed on the NASDAQ. Founder Chip Wilson holds a single-digit stake; the largest shareholders are US institutional funds (FMR, Vanguard, BlackRock). Canadian by address and origin, American by incorporation and shareholder base — a real split rather than a gap in our research.", confidence: "verify",
    alternatives: ["Aritzia (Canadian, TSX: ATZ)", "Roots", "Kotn"] },
  "aritzia.com": { brand: "Aritzia", ownership: "Canada", category: "Apparel & Fashion", hq: "Vancouver, BC", note: "TSX: ATZ", confidence: "high",
    alternatives: [] },
  "canadagoose.com": { brand: "Canada Goose", ownership: "Canada", category: "Apparel & Fashion", hq: "Toronto, Ontario", note: "TSX/NYSE: GOOS — dual-listed but Canadian headquartered and founded", confidence: "high",
    alternatives: [] },
  "roots.com": { brand: "Roots", ownership: "Canada", category: "Apparel & Fashion", hq: "Toronto, Ontario", note: "TSX: ROOT", confidence: "high",
    alternatives: [] },
  "spotify.com": { brand: "Spotify", ownership: "not-US", category: "Media & Entertainment", hq: "Stockholm, Sweden", note: "Not US-owned — Swedish company, NYSE listing is just where it trades, not where it's owned/controlled", confidence: "high",
    alternatives: ["CBC Music"] },
  "sportchek.ca": { brand: "Sport Chek", ownership: "Canada", category: "Apparel & Fashion", hq: "Toronto, Ontario", note: "Owned by Canadian Tire Corporation, TSX: CTC", confidence: "high",
    alternatives: [] },
  "marks.com": { brand: "Mark's", ownership: "Canada", category: "Apparel & Fashion", hq: "Calgary, Alberta", note: "Owned by Canadian Tire Corporation, TSX: CTC", confidence: "high",
    alternatives: [] },
  "saveonfoods.com": { brand: "Save-On-Foods", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Langley, BC", note: "Owned by Jim Pattison Group, a privately held Canadian conglomerate", confidence: "high",
    alternatives: [] },
  "iga.net": { brand: "IGA (Quebec)", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Montreal, Quebec", note: "Quebec banner of Sobeys, owned by Empire Company Ltd.", confidence: "high",
    alternatives: [] },
  "gianttiger.com": { brand: "Giant Tiger", ownership: "Canada", category: "Retail & Department Stores", hq: "Ottawa, Ontario", note: "Privately held, Canadian-owned since 1961", confidence: "high",
    alternatives: [] },
  "londondrugs.com": { brand: "London Drugs", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Richmond, BC", note: "Privately held, Canadian-owned", confidence: "high",
    alternatives: [] },
  "doordash.com": { brand: "DoorDash", ownership: "US", category: "Food & Drink", hq: "San Francisco, California", note: "NASDAQ: DASH", confidence: "high",
    alternatives: ["local delivery services"] },
  "disneyplus.com": { brand: "Disney+", ownership: "US", category: "Media & Entertainment", hq: "Burbank, California", note: "NYSE: DIS", confidence: "high",
    alternatives: ["CBC Gem", "Crave"] },
  "hulu.com": { brand: "Hulu", ownership: "US", category: "Media & Entertainment", hq: "Santa Monica, California", note: "Owned by The Walt Disney Company, NYSE: DIS", confidence: "high",
    alternatives: ["CBC Gem", "Crave"] },
  "primevideo.com": { brand: "Amazon Prime Video", ownership: "US", category: "Media & Entertainment", hq: "Seattle, Washington", note: "NASDAQ: AMZN", confidence: "high",
    alternatives: ["CBC Gem", "Crave"] },
  "airbnb.com": { brand: "Airbnb", ownership: "US", category: "Travel & Transportation", hq: "San Francisco, California", note: "NASDAQ: ABNB", confidence: "high",
    alternatives: [] },
  "expedia.ca": { brand: "Expedia", ownership: "US", category: "Travel & Transportation", hq: "Seattle, Washington", note: "NASDAQ: EXPE", confidence: "high",
    alternatives: ["FlightHub (Canadian)", "Air Canada Vacations"] },

  // ---- Canadian-owned ----
  "crave.ca": { brand: "Crave", ownership: "Canada", category: "Media & Entertainment", hq: "Toronto, Ontario", note: "Owned by Bell Media (BCE Inc.), the largest Canadian-owned streaming service", confidence: "high",
    alternatives: [] },
  "cbc.ca": { brand: "CBC / CBC Gem", ownership: "Canada", category: "Media & Entertainment", hq: "Toronto, Ontario", note: "Crown corporation, publicly owned by the Government of Canada", confidence: "high",
    alternatives: [] },
  "manulife.ca": { brand: "Manulife", ownership: "Canada", category: "Banking & Insurance", hq: "Toronto, Ontario", note: "TSX: MFC", confidence: "high",
    alternatives: [] },
  "sunlife.ca": { brand: "Sun Life", ownership: "Canada", category: "Banking & Insurance", hq: "Toronto, Ontario", note: "TSX: SLF", confidence: "high",
    alternatives: [] },
  "desjardins.com": { brand: "Desjardins", ownership: "Canada", category: "Banking & Insurance", hq: "Levis, Quebec", note: "Cooperative financial group, member-owned, largest credit union in Canada", confidence: "high",
    alternatives: [] },
  "flighthub.com": { brand: "FlightHub", ownership: "Canada", category: "Travel & Transportation", hq: "Montreal, Quebec", note: "Subsidiary of Momentum Ventures, co-founded by Matt Keezer. Confirmed Canadian via multiple independent business profiles and the company's own press materials.", confidence: "high",
    alternatives: [] },
  "petro-canada.ca": { brand: "Petro-Canada", ownership: "Canada", category: "Gas & Convenience", hq: "Calgary, Alberta", note: "Owned by Suncor Energy, TSX/NYSE: SU. Suncor considered selling the retail network in 2022 under investor pressure (Elliott Management) but decided to keep it. A 2024 report noted the CEO left the door open to reconsidering, but no sale has occurred as of this research. Worth re-checking periodically given that history.", confidence: "high",
    alternatives: [] },
  "circlek.ca": { brand: "Circle K", ownership: "Canada", category: "Gas & Convenience", hq: "Laval, Quebec", note: "Owned by Alimentation Couche-Tard, TSX: ATD — Canadian-headquartered global convenience store operator", confidence: "high",
    alternatives: [] },
  "7-eleven.ca": { brand: "7-Eleven", ownership: "not-US", category: "Gas & Convenience", hq: "Tokyo, Japan (parent)", note: "Not US-owned — parent is Seven & i Holdings, a Japanese company. Not Canadian either.", confidence: "high",
    alternatives: ["Circle K", "Petro-Canada", "Couche-Tard-owned stores"] },
  "esso.ca": { brand: "Esso", ownership: "US", category: "Gas & Convenience", hq: "Irving, Texas", note: "Owned by Exxon Mobil (Imperial Oil is the Canadian operating subsidiary, but Exxon Mobil holds a majority stake), NYSE: XOM", confidence: "high",
    alternatives: ["Petro-Canada", "Circle K"] },
  "shell.ca": { brand: "Shell", ownership: "not-US", category: "Gas & Convenience", hq: "London, UK", note: "Not US-owned — UK-headquartered (Shell plc). Not Canadian either.", confidence: "high",
    alternatives: ["Petro-Canada", "Circle K"] },
  "intactfinancial.com": { brand: "Intact Insurance", ownership: "Canada", category: "Banking & Insurance", hq: "Toronto, Ontario", note: "TSX: IFC — largest property and casualty insurer in Canada", confidence: "high",
    alternatives: [] },
  "cooperators.ca": { brand: "Co-operators", ownership: "Canada", category: "Banking & Insurance", hq: "Guelph, Ontario", note: "Canadian-owned cooperative insurance and financial services group", confidence: "high",
    alternatives: [] },
  "allstate.ca": { brand: "Allstate Canada", ownership: "US", category: "Banking & Insurance", hq: "Northbrook, Illinois", note: "Subsidiary of The Allstate Corporation, NYSE: ALL", confidence: "high",
    alternatives: ["Intact Insurance", "Co-operators", "Desjardins Insurance"] },
  "jeancoutu.com": { brand: "Jean Coutu", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Longueuil, Quebec", note: "Acquired by Metro Inc. in 2018, TSX: MRU", confidence: "high",
    alternatives: [] },
  "pharmasave.com": { brand: "Pharmasave", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Vancouver, BC", note: "Member-owned Canadian pharmacy cooperative/franchise", confidence: "high",
    alternatives: [] },
  "herschel.com": { brand: "Herschel Supply Co.", ownership: "Canada", category: "Apparel & Fashion", hq: "Vancouver, BC", note: "Founded 2009 by Lyndon and Jamie Cormack, privately held", confidence: "high",
    alternatives: [] },
  "tilley.com": { brand: "Tilley", ownership: "Canada", category: "Apparel & Fashion", hq: "Don Mills, Ontario", note: "Privately held Canadian outdoor apparel brand", confidence: "high",
    alternatives: [] },
  "mackage.com": { brand: "Mackage", ownership: "US", category: "Apparel & Fashion", hq: "Montreal, Quebec (design and operations) / New York, New York (Lee Equity Partners)", note: "Resolved — the earlier conflict was that both sources were partly right. Mackage's parent really is APP Group of Montreal (which also owns Soia & Kyo), but APP Group is itself majority-owned by InterLuxe Holdings, the consumer-brand arm of New York's Lee Equity Partners, following its 2017 investment. Other major shareholders include SK Holdings of Korea and a fund of the Montreal transit pension plans; founders Eran Elfassy and Elisa Dahan retain the largest minority stakes. Design and operations stay in Montreal, but control is American.", confidence: "high",
    alternatives: ["Canada Goose", "Nobis (Canadian outerwear)"] },
  "frankandoak.com": { brand: "Frank And Oak", ownership: "US", category: "Apparel & Fashion", hq: "Montreal, Quebec (operations) / New York, New York (Unified Commerce Group)", note: "Canadian-founded (Montreal, 2012) but acquired out of bankruptcy protection by Unified Commerce Group, a New York-based retail acquisition firm, in October 2020. Stores and operations remain Canadian-facing, but ownership is US. Confirmed via multiple independent business press reports on the 2020 acquisition and UCG's own statements.", confidence: "high",
    alternatives: ["Kotn (Canadian)", "Naked & Famous Denim (Canadian)"] },
  "reitmans.com": { brand: "Reitmans", ownership: "Canada", category: "Apparel & Fashion", hq: "Montreal, Quebec", note: "TSX: RET.A — Canadian women's clothing retailer since 1926", confidence: "high",
    alternatives: [] },
  "harrys.com": { brand: "Harry Rosen", ownership: "Canada", category: "Apparel & Fashion", hq: "Toronto, Ontario", note: "Privately held, family-owned Canadian menswear retailer since 1954. Larry Rosen (son of founder Harry Rosen) actively leads the company; celebrated 70 years family-run in 2024 with no indication of a sale. Confirmed via multiple independent business press profiles.", confidence: "high",
    alternatives: [] },
  "simons.ca": { brand: "Simons", ownership: "Canada", category: "Retail & Department Stores", hq: "Quebec City, Quebec", note: "Privately held, family-owned Canadian department store since 1840", confidence: "high",
    alternatives: [] },
  "hbc.com": { brand: "Hudson's Bay / The Bay", ownership: "Canada", category: "Retail & Department Stores", hq: "Toronto, Ontario", note: "Resolved: the brand is Canadian-owned again, by a different Canadian company. After HBC filed for CCAA protection in March 2025 and liquidated its 355-year-old store network, an Ontario court approved the sale of the Hudson's Bay intellectual property to Canadian Tire Corporation (TSX: CTC) for $30M on June 3, 2025 — the coat of arms, the multi-stripe pattern, the Bay Days and Distinctly Home names, the domains and the customer data. Canadian Tire beat 16 other bidders. The former operating company was renamed Rupert Legacy and is winding down. So the trademarks live on under Canadian ownership, but the department stores are gone.", confidence: "high",
    alternatives: [] },
  "freedommobile.ca": { brand: "Freedom Mobile", ownership: "Canada", category: "Telecom & Mobile", hq: "Toronto, Ontario", note: "Owned by Videotron (a Quebecor subsidiary) since April 2023, after being owned by Shaw 2016–2023. Confirmed via Quebecor/Shaw joint announcement and Canadian government (ISED) regulatory filing.", confidence: "high",
    alternatives: [] },
  "fido.ca": { brand: "Fido", ownership: "Canada", category: "Telecom & Mobile", hq: "Toronto, Ontario", note: "Owned by Rogers Communications, TSX: RCI.B", confidence: "high",
    alternatives: [] },
  "koodomobile.com": { brand: "Koodo", ownership: "Canada", category: "Telecom & Mobile", hq: "Vancouver, BC", note: "Owned by Telus, TSX: T", confidence: "high",
    alternatives: [] },
  "virginplus.ca": { brand: "Virgin Plus", ownership: "Canada", category: "Telecom & Mobile", hq: "Toronto, Ontario", note: "Owned by Bell (BCE Inc.) — 'Virgin' is a licensed brand name only, not UK/Virgin Group ownership", confidence: "high",
    alternatives: [] },
  "publicmobile.ca": { brand: "Public Mobile", ownership: "Canada", category: "Telecom & Mobile", hq: "Toronto, Ontario", note: "Owned by Telus, TSX: T", confidence: "high",
    alternatives: [] },
  "chatrmobile.com": { brand: "Chatr Mobile", ownership: "Canada", category: "Telecom & Mobile", hq: "Toronto, Ontario", note: "Owned by Rogers Communications, TSX: RCI.B", confidence: "high",
    alternatives: [] },
  "nbc.ca": { brand: "National Bank of Canada", ownership: "Canada", category: "Banking & Insurance", hq: "Montreal, Quebec", note: "TSX: NA", confidence: "high",
    alternatives: [] },
  "sleepcountry.ca": { brand: "Sleep Country Canada", ownership: "Canada", category: "Home & Furniture", hq: "Brampton, Ontario", note: "TSX: ZZZ", confidence: "high",
    alternatives: [] },
  "leons.ca": { brand: "Leon's Furniture", ownership: "Canada", category: "Home & Furniture", hq: "Toronto, Ontario", note: "TSX: LNF", confidence: "high",
    alternatives: [] },
  "thebrick.com": { brand: "The Brick", ownership: "Canada", category: "Home & Furniture", hq: "Edmonton, Alberta", note: "Owned by Leon's Furniture, TSX: LNF, since 2013", confidence: "high",
    alternatives: [] },
  "structube.com": { brand: "Structube", ownership: "Canada", category: "Home & Furniture", hq: "Montreal, Quebec", note: "Privately held Canadian furniture retailer", confidence: "high",
    alternatives: [] },
  "eq3.com": { brand: "EQ3", ownership: "Canada", category: "Home & Furniture", hq: "Winnipeg, Manitoba", note: "Owned by Palliser Furniture, a privately held Canadian company", confidence: "high",
    alternatives: [] },
  "partycity.ca": { brand: "Party City Canada", ownership: "Canada", category: "Retail & Department Stores", hq: "Toronto, Ontario", note: "Canadian retail business and stores acquired by Canadian Tire Corporation in 2019 for $174.4M — the brand name is US in origin but the Canadian retail operation itself is Canadian Tire-owned. Confirmed via CTC's own announcement and multiple independent business press reports.", confidence: "high",
    alternatives: [] },
  "michaels.com": { brand: "Michaels", ownership: "US", category: "Retail & Department Stores", hq: "Irving, Texas", note: "Owned by Apollo Global Management, a US private equity firm", confidence: "high",
    alternatives: ["DeSerres (Canadian craft retailer)"] },
  "gap.com": { brand: "Gap / Old Navy / Banana Republic", ownership: "US", category: "Apparel & Fashion", hq: "San Francisco, California", note: "Gap Inc., NYSE: GAP", confidence: "high",
    alternatives: ["Aritzia", "Roots"] },
  "sephora.com": { brand: "Sephora", ownership: "not-US", category: "Personal Care & Household", hq: "Paris, France", note: "Owned by LVMH — French, not US-owned. Not Canadian either.", confidence: "high",
    alternatives: [] },
  "hm.com": { brand: "H&M", ownership: "not-US", category: "Apparel & Fashion", hq: "Stockholm, Sweden", note: "Not US-owned — Swedish company. Not Canadian either.", confidence: "high",
    alternatives: [] },
  "zara.com": { brand: "Zara", ownership: "not-US", category: "Apparel & Fashion", hq: "Arteixo, Spain", note: "Owned by Inditex — Spanish, not US-owned. Not Canadian either.", confidence: "high",
    alternatives: [] },
  "aldoshoes.com": { brand: "Aldo", ownership: "Canada", category: "Apparel & Fashion", hq: "Montreal, Quebec", note: "Privately held Canadian footwear and accessories retailer", confidence: "high",
    alternatives: [] },
  "kijiji.ca": { brand: "Kijiji", ownership: "not-US", category: "Tech & Online Services", hq: "Toronto, Ontario (Canadian operations) / owned by Adevinta, Norway", note: "Not US-owned — Adevinta is a Norwegian global classifieds company (Oslo-listed). Not Canadian-owned either, despite the Canadian operational HQ.", confidence: "high",
    alternatives: ["Facebook Marketplace is also not Canadian (US/Meta) — no major Canadian-owned classifieds alternative at this scale"] },
  "airtransat.com": { brand: "Air Transat", ownership: "Canada", category: "Travel & Transportation", hq: "Montreal, Quebec", note: "Owned by Transat A.T. Inc., TSX: TRZ. Air Canada's proposed 2019 acquisition was terminated by mutual agreement in April 2021 after EU regulators indicated they would not approve it — Transat remains independent and Canadian. Confirmed via Air Canada's own press release.", confidence: "high",
    alternatives: [] },
  "sunwing.ca": { brand: "Sunwing", ownership: "Canada", category: "Travel & Transportation", hq: "Toronto, Ontario", note: "Acquired by WestJet (itself owned by Onex Corporation, a Canadian PE firm) in May 2023. Previously majority-owned by the Hunter family (51%) with TUI Group (Germany) holding 49% — that structure was superseded by the WestJet acquisition. Confirmed via multiple independent news reports.", confidence: "high",
    alternatives: [] },
  "autotrader.ca": { brand: "AutoTrader.ca / AutoHebdo", ownership: "US", category: "Tech & Online Services", hq: "Toronto, Ontario (operations) / San Francisco, California (Hellman & Friedman)", note: "Resolved, through a three-country ownership chain. AutoTrader.ca is run by TRADER Corporation of Toronto, which US private equity firm Thoma Bravo sold in December 2024 to AutoScout24, a German marketplace operator. AutoScout24 is itself majority-owned by Hellman & Friedman, a San Francisco private equity firm, which put additional equity into the deal. So the site is Canadian-operated under a German company that is US-controlled — following the chain to whoever actually holds control lands on the US.", confidence: "high",
    alternatives: [] },
  "canadacomputers.com": { brand: "Canada Computers & Electronics", ownership: "Canada", category: "Retail & Department Stores", hq: "Markham, Ontario", note: "Privately held Canadian electronics retailer", confidence: "high",
    alternatives: [] },
  "memoryexpress.com": { brand: "Memory Express", ownership: "Canada", category: "Retail & Department Stores", hq: "Burnaby, BC", note: "Privately held Canadian electronics retailer", confidence: "high",
    alternatives: [] },
  "endy.com": { brand: "Endy", ownership: "Canada", category: "Home & Furniture", hq: "Toronto, Ontario", note: "Owned by Sleep Country Canada Holdings, TSX: ZZZ, since 2018", confidence: "high",
    alternatives: [] },
  "casper.com": { brand: "Casper", ownership: "US", category: "Home & Furniture", hq: "New York, New York", note: "Taken private by Durational Capital Management (US) in 2022. Note: Casper's Canadian retail operations and assets were separately acquired by Sleep Country Canada — the Canadian business specifically is now Canadian-owned even though the global Casper brand/US parent is not.", confidence: "high",
    alternatives: ["Endy (also Sleep Country-owned)"] },
  "booking.com": { brand: "Booking.com", ownership: "US", category: "Travel & Transportation", hq: "Norwalk, Connecticut", note: "Owned by Booking Holdings (formerly Priceline), NASDAQ: BKNG", confidence: "high",
    alternatives: [] },
  "tripadvisor.ca": { brand: "TripAdvisor", ownership: "US", category: "Travel & Transportation", hq: "Needham, Massachusetts", note: "NASDAQ: TRIP", confidence: "high",
    alternatives: [] },
  "fairmont.com": { brand: "Fairmont Hotels", ownership: "not-US", category: "Travel & Transportation", hq: "Paris, France (Accor)", note: "Genuinely interesting history: originally Canadian (Canadian Pacific Hotels acquired majority interest in 1999), but the Fairmont brand was later sold and is now owned by Accor, a French hospitality group — not US-owned, and no longer Canadian-owned either despite the brand's Canadian roots and many landmark Canadian properties (Banff Springs, Château Frontenac).", confidence: "high",
    alternatives: [] },

  // ---- Everyday household / personal care (small-ticket, high switching willingness) ----
  "tide.com": { brand: "Tide", ownership: "US", category: "Personal Care & Household", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: ["Nellie's (Canadian laundry powder)", "Attitude (Canadian, Quebec-based)"] },
  "dove.com": { brand: "Dove", ownership: "not-US", category: "Personal Care & Household", hq: "London, UK / Rotterdam, Netherlands", note: "Owned by Unilever — Anglo-Dutch, not US-owned. Not Canadian either.", confidence: "high",
    alternatives: ["Attitude (Canadian personal care)"] },
  "herbalessences.com": { brand: "Herbal Essences", ownership: "US", category: "Personal Care & Household", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: ["Attitude (Canadian natural haircare)", "Druide (Canadian, Quebec-based)"] },
  "nivea.ca": { brand: "Nivea", ownership: "not-US", category: "Personal Care & Household", hq: "Hamburg, Germany", note: "Owned by Beiersdorf AG — German, not US-owned. Not Canadian either.", confidence: "high",
    alternatives: ["Province Apothecary (Canadian skincare)"] },
  "thebodyshop.com": { brand: "The Body Shop", ownership: "not-US", category: "Personal Care & Household", hq: "London, United Kingdom", note: "Resolved: after the 2024 collapse into administration, a consortium led by Aurea Group — the London growth-capital firm co-founded by Mike Jatania and Paul Raphael — completed the purchase of The Body Shop's international assets in September 2024, including the North American business. Jatania is executive chairman. British-owned; not US-owned and not Canadian.", confidence: "high",
    alternatives: ["Rocky Mountain Soap Company (Canadian)", "Province Apothecary (Canadian)", "Saje Natural Wellness (Canadian)"] },
  "attitudeliving.com": { brand: "Attitude", ownership: "Canada", category: "Personal Care & Household", hq: "Beloeil, Quebec", note: "Privately held Canadian personal care and household cleaning brand", confidence: "high",
    alternatives: [] },
  "nelliesclean.ca": { brand: "Nellie's", ownership: "Canada", category: "Personal Care & Household", hq: "Ontario", note: "Privately held Canadian natural laundry and cleaning brand", confidence: "high",
    alternatives: [] },
  "provinceapothecary.com": { brand: "Province Apothecary", ownership: "Canada", category: "Personal Care & Household", hq: "Toronto, Ontario", note: "Privately held Canadian natural skincare brand", confidence: "high",
    alternatives: [] },
  "kotn.com": { brand: "Kotn", ownership: "Canada", category: "Apparel & Fashion", hq: "Toronto, Ontario", note: "Privately held Canadian ethical basics/clothing brand, founded 2015", confidence: "high",
    alternatives: [] },
  "nakedandfamous.com": { brand: "Naked & Famous Denim", ownership: "Canada", category: "Apparel & Fashion", hq: "Montreal, Quebec", note: "Privately held Canadian denim brand — jeans cut, made, and sewn in Canada", confidence: "high",
    alternatives: [] },
  "peacecollective.com": { brand: "Peace Collective", ownership: "Canada", category: "Apparel & Fashion", hq: "Toronto, Ontario", note: "Privately held Canadian clothing brand, founded 2014", confidence: "high",
    alternatives: [] },
  "kickinghorsecoffee.com": { brand: "Kicking Horse Coffee", ownership: "not-US", category: "Food & Drink", hq: "Invermere, BC (operations) / Turin, Italy (Lavazza Group)", note: "80% owned by Lavazza Group (Italy) since May 2017, purchased from Swander Pace Capital. Founder Elana Rosenfeld retains 20% and remains CEO. Not US-owned, but no longer majority Canadian-owned either — a common misconception given the strong Canadian brand identity. Confirmed via Lavazza's own 2017 acquisition announcement.", confidence: "high",
    alternatives: ["Ethical Bean Coffee (Canadian)", "Van Houtte (Canadian roots, now Keurig Dr Pepper-owned — verify before recommending)"] },
  "levis.com": { brand: "Levi's", ownership: "US", category: "Apparel & Fashion", hq: "San Francisco, California", note: "Levi Strauss & Co., NYSE: LEVI", confidence: "high",
    alternatives: ["Naked & Famous Denim"] },
  "oldspice.com": { brand: "Old Spice", ownership: "US", category: "Personal Care & Household", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: ["Attitude (Canadian personal care)"] },
  "crest.com": { brand: "Crest", ownership: "US", category: "Personal Care & Household", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: [] },
  "colgate.com": { brand: "Colgate", ownership: "US", category: "Personal Care & Household", hq: "New York, New York", note: "Colgate-Palmolive, NYSE: CL", confidence: "high",
    alternatives: [] },
  "vanhoutte.com": { brand: "Van Houtte", ownership: "US", category: "Food & Drink", hq: "Montreal, Quebec (operations) / Burlington, Massachusetts (Keurig Dr Pepper)", note: "Despite very strong Canadian brand identity (founded Montreal 1919, marketed as an 'iconic Canadian brand'), Van Houtte has been owned by US-based Keurig Dr Pepper since 2010 (acquired by Green Mountain Coffee Roasters, which later merged into Keurig Dr Pepper). Confirmed via the original 2010 acquisition announcements and Keurig Canada's own press materials.", confidence: "high",
    alternatives: ["Kicking Horse Coffee (Lavazza/Italian-owned, not Canadian, but also not US)", "look for smaller independent Canadian roasters"] },
  "pantene.com": { brand: "Pantene", ownership: "US", category: "Personal Care & Household", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: ["Attitude (Canadian)", "Druide (Canadian)"] },
  "suave.com": { brand: "Suave", ownership: "not-US", category: "Personal Care & Household", hq: "London, UK / Rotterdam, Netherlands", note: "Owned by Unilever — Anglo-Dutch, not US-owned. Not Canadian either.", confidence: "high",
    alternatives: ["Attitude (Canadian)"] },
  "dawn-dish.com": { brand: "Dawn", ownership: "US", category: "Personal Care & Household", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: ["Attitude (Canadian dish soap)", "Bio-Vert (Canadian, Quebec-based)"] },
  "palmolive.com": { brand: "Palmolive", ownership: "US", category: "Personal Care & Household", hq: "New York, New York", note: "Colgate-Palmolive, NYSE: CL", confidence: "high",
    alternatives: ["Attitude (Canadian dish soap)"] },
  "pampers.com": { brand: "Pampers", ownership: "US", category: "Personal Care & Household", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: ["Royale (Irving Consumer Products, Canadian — launched diapers in 2024, self-described as 'the only Canadian manufacturer of diapers')"] },
  "huggies.com": { brand: "Huggies", ownership: "US", category: "Personal Care & Household", hq: "Irving, Texas", note: "Owned by Kimberly-Clark, NYSE: KMB", confidence: "high",
    alternatives: ["Royale (Irving Consumer Products, Canadian — launched diapers in 2024, self-described as 'the only Canadian manufacturer of diapers')"] },
  "royale.ca": { brand: "Royale", ownership: "Canada", category: "Personal Care & Household", hq: "Dieppe, New Brunswick", note: "Made by Irving Consumer Products, a privately held Canadian company (Irving family, New Brunswick). Royale has made tissue products for 60+ years and launched a diaper line in 2024. Confirmed via Irving Consumer Products' own press release, which specifically states Royale is 'the only Canadian manufacturer of diapers.'", confidence: "high",
    alternatives: [] },
  "presidentschoice.ca": { brand: "President's Choice", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Brampton, Ontario", note: "Owned by Loblaw Companies / George Weston Limited — Canada's largest private-label grocery brand", confidence: "high",
    alternatives: [] },
  "compliments.ca": { brand: "Compliments", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Stellarton, Nova Scotia", note: "Private-label brand owned by Sobeys / Empire Company Ltd.", confidence: "high",
    alternatives: [] },
  "lays.com": { brand: "Lay's / Doritos", ownership: "US", category: "Food & Drink", hq: "Purchase, New York", note: "Owned by PepsiCo (Frito-Lay division), NASDAQ: PEP", confidence: "high",
    alternatives: ["Nature's Path (Canadian, family-owned)", "President's Choice or Compliments-brand chips (Canadian private label)"] },
  "kraftheinz.com": { brand: "Kraft Heinz", ownership: "US", category: "Food & Drink", hq: "Chicago, Illinois / Pittsburgh, Pennsylvania", note: "NASDAQ: KHC", confidence: "high",
    alternatives: ["Maple Leaf Foods (Canadian)", "President's Choice (Canadian private label)"] },
  "kelloggs.com": { brand: "Kellogg's", ownership: "US", category: "Food & Drink", hq: "Battle Creek, Michigan", note: "Now branded Kellanova after 2023 split, NYSE: K", confidence: "high",
    alternatives: ["Nature's Path (Canadian, family-owned organic cereal)", "President's Choice (Canadian private label)"] },
  "generalmills.com": { brand: "General Mills", ownership: "US", category: "Food & Drink", hq: "Minneapolis, Minnesota", note: "NYSE: GIS", confidence: "high",
    alternatives: ["Nature's Path (Canadian, family-owned organic cereal)", "President's Choice (Canadian private label)"] },

  // ---- Beer, spirits and soft drinks ----
  // Note: this cluster is where "sounds Canadian, isn't" is most common —
  // Canada Dry, Labatt and Sleeman are all frequently assumed to be
  // Canadian-owned and none of them are.
  "canadadry.com": { brand: "Canada Dry", ownership: "US", category: "Food & Drink", hq: "Burlington, Massachusetts / Frisco, Texas (Keurig Dr Pepper)", note: "The name says Canada and the brand genuinely started there — invented in Toronto in 1904 by John J. McLaughlin — but it has not been Canadian-owned since 1986, when it went to Cadbury Schweppes (UK). US-owned since the 2008 Dr Pepper Snapple split, and part of Keurig Dr Pepper (NASDAQ: KDP) since the 2018 Keurig merger. Ownership chain confirmed via KDP's SEC filings and the documented sale history.", confidence: "high",
    alternatives: [], alternativesNote: "No Canadian-owned ginger ale at national scale that we've verified yet. Provincial craft soda makers exist — tell us about one and we'll research it." },
  "labatt.com": { brand: "Labatt", ownership: "not-US", category: "Food & Drink", hq: "Toronto, Ontario (operations) / Leuven, Belgium (AB InBev)", note: "Founded in London, Ontario in 1847 and still brewed in Canada, but Canadian ownership ended in 1995 when Belgian brewer Interbrew bought it. Interbrew became InBev (2004) and then Anheuser-Busch InBev (2008), a Belgian company. Not US-owned, but not Canadian-owned either — Budweiser, Stella Artois and Corona share the same parent. Confirmed via AB InBev's SEC 20-F filings, which state Belgian incorporation.", confidence: "high",
    alternatives: ["Moosehead (the last major Canadian-owned brewery)"] },
  "sleeman.ca": { brand: "Sleeman", ownership: "not-US", category: "Food & Drink", hq: "Guelph, Ontario (operations) / Tokyo, Japan (Sapporo)", note: "Founded in Guelph in 1834 and revived by John Sleeman in 1988, but acquired outright by Sapporo Breweries (Japan) in 2006 for $400M — the first major Japanese acquisition of a Canadian brewery. Still brewed in Guelph and marketed on its Canadian heritage, but wholly owned by Sapporo. Not US-owned, not Canadian-owned. Confirmed via Globe and Mail and CBC reporting on the 2006 takeover.", confidence: "high",
    alternatives: ["Moosehead (the last major Canadian-owned brewery)"] },
  "molsoncoors.com": { brand: "Molson Coors", ownership: "verify", category: "Food & Drink", hq: "Chicago, Illinois / Golden, Colorado / Montreal, Quebec", note: "Checked, and binational on purpose — this flag is the finding. Molson, founded in Montreal in 1786 and Canada's oldest brewery, merged with Colorado's Coors in 2005 as a genuine merger rather than a takeover. The combined company is US-incorporated and primarily listed on the NYSE (TAP), while Molson Coors Canada trades on the TSX (TPX.B), and the Molson and Coors families both retain governance rights through a dual-class structure. Calling it either Canadian or American would misrepresent how it was deliberately built.", confidence: "verify",
    alternatives: ["Moosehead Breweries (Canadian, independent, Saint John NB)", "Steam Whistle (Canadian)", "local craft breweries"] },

  // ---- Canadian-owned food and drink ----
  "moosehead.ca": { brand: "Moosehead Breweries", ownership: "Canada", category: "Food & Drink", hq: "Saint John, New Brunswick", note: "Privately held by the Oland family since 1867, now in its sixth generation — widely described as the last major Canadian-owned brewery, after Molson, Labatt and Sleeman all passed into foreign ownership. Independent of any multinational parent. Confirmed via the company's own materials plus independent brewing-industry profiles.", confidence: "high",
    alternatives: [] },
  "saputo.com": { brand: "Saputo", ownership: "Canada", category: "Food & Drink", hq: "Montreal, Quebec", note: "TSX: SAP — one of the ten largest dairy processors in the world, founded in Montreal in 1954 by the Saputo family, who still control roughly 60% of the shares. Makes cheese and dairy under Saputo, Armstrong, Dairyland and other banners.", confidence: "high",
    alternatives: [] },
  "mapleleaffoods.com": { brand: "Maple Leaf Foods", ownership: "Canada", category: "Food & Drink", hq: "Mississauga, Ontario", note: "TSX: MFI — Canadian protein and packaged-meats company (Maple Leaf, Schneiders, Greenfield Natural Meat, Lightlife). The McCain family holds roughly 40% of shares. Spun off its pork operations as Canada Packers Inc. in 2025. Confirmed via the company's own Annual Information Form filed on SEDAR+.", confidence: "high",
    alternatives: [] },
  "mccain.ca": { brand: "McCain Foods", ownership: "Canada", category: "Food & Drink", hq: "Florenceville, New Brunswick (founding home) / Toronto, Ontario", note: "Privately held by the McCain family, founded in Florenceville, New Brunswick in 1957. The world's largest manufacturer of frozen potato products — roughly one in four french fries globally. Remains private and Canadian-controlled.", confidence: "high",
    alternatives: [] },
  "naturespath.com": { brand: "Nature's Path", ownership: "Canada", category: "Food & Drink", hq: "Richmond, British Columbia", note: "Privately held and family-owned, founded in 1985 by Arran and Ratana Stephens and now led by the next generation. North America's largest producer of certified organic breakfast and snack foods; also owns EnviroKidz, Que Pasa, Anita's Organic Mill and Love Child Organics. Deliberately independent — the family has publicly declined acquisition offers.", confidence: "high",
    alternatives: [] },
  "aw.ca": { brand: "A&W Canada", ownership: "Canada", category: "Food & Drink", hq: "North Vancouver, British Columbia", note: "A genuine split-brand case worth knowing: A&W's Canadian business was sold away from the US chain in 1972 and has operated as a separate Canadian company ever since — it only licenses the trademarks. In October 2024 A&W Food Services of Canada and the A&W Revenue Royalties Income Fund combined into a single Canadian public company (TSX: AW). The US A&W chain is separately owned and unrelated to the Canadian operator. Confirmed via the combination's SEDAR+ filings and company announcements.", confidence: "high",
    alternatives: [] },
  "bostonpizza.com": { brand: "Boston Pizza", ownership: "Canada", category: "Food & Drink", hq: "Richmond, British Columbia", note: "Canadian despite the American-sounding name — the reverse of the usual problem. Founded in Edmonton in 1964 and headquartered in Richmond, BC; the largest casual dining chain in Canada, franchised to locally owned operators. The associated royalties fund trades on the TSX (BPF.UN).", confidence: "high",
    alternatives: [] },
  "swisschalet.com": { brand: "Swiss Chalet", ownership: "Canada", category: "Food & Drink", hq: "Vaughan, Ontario", note: "Owned by Recipe Unlimited (formerly Cara), Canada's oldest and largest full-service restaurant company, taken private in 2022 by Fairfax Financial Holdings (TSX: FFH), a Toronto-based Canadian company. The Phelan family, which founded Cara, retains a stake through Cara Holdings. Swiss/Ontario naming aside, ownership is Canadian.", confidence: "high",
    alternatives: [] },
  "harveys.ca": { brand: "Harvey's", ownership: "Canada", category: "Food & Drink", hq: "Vaughan, Ontario", note: "Owned by Recipe Unlimited, which is controlled by Fairfax Financial Holdings (TSX: FFH), a Canadian company based in Toronto. Same Canadian ownership chain as Swiss Chalet, Montana's, Kelseys and East Side Mario's.", confidence: "high",
    alternatives: [] },
  "kegsteakhouse.com": { brand: "The Keg", ownership: "Canada", category: "Food & Drink", hq: "Richmond, British Columbia", note: "Founded in Vancouver in 1971, acquired by Recipe Unlimited in 2018 and now held under Fairfax Financial Holdings (TSX: FFH), a Canadian company — Fairfax retained ownership when The Keg was separated out from Recipe in 2025.", confidence: "high",
    alternatives: [] },
  "pizzapizza.ca": { brand: "Pizza Pizza", ownership: "Canada", category: "Food & Drink", hq: "Toronto, Ontario", note: "Founded in Toronto in 1967 and Canadian-owned throughout; the associated royalty company trades on the TSX (PZA). Also operates Pizza 73, mainly in Alberta.", confidence: "high",
    alternatives: [] },
  "secondcup.com": { brand: "Second Cup", ownership: "Canada", category: "Food & Drink", hq: "Montreal, Quebec (Foodtastic)", note: "Canada's largest specialty coffee chain after Tim Hortons, sold by Aegis Brands to Foodtastic, a privately held Quebec restaurant franchising group, in February 2021. Canadian-owned before and after that sale. Confirmed via CBC, Globe and Mail reporting plus the closing announcement.", confidence: "high",
    alternatives: [] },

  // ---- News/media ----
  "nationalpost.com": { brand: "National Post / Financial Post", ownership: "US", category: "Media & Entertainment", hq: "Toronto, Ontario (operations) / Chatham Borough, New Jersey (Chatham Asset Management)", note: "Owned by Postmedia Network, which is 63-66% owned by Chatham Asset Management, an American hedge fund — despite widespread perception as a purely Canadian newspaper chain. Confirmed via Postmedia's own SEDAR/TSX disclosures and multiple independent news reports (Globe and Mail, Wikipedia citing primary sources).", confidence: "high",
    alternatives: ["The Globe and Mail (Canadian, Woodbridge/Thomson family-owned)", "CBC News"] },
  "theglobeandmail.com": { brand: "The Globe and Mail", ownership: "Canada", category: "Media & Entertainment", hq: "Toronto, Ontario", note: "Owned by The Woodbridge Company (Thomson family), a privately held Canadian company", confidence: "high",
    alternatives: [] },
  "globalnews.ca": { brand: "Global News", ownership: "Canada", category: "Media & Entertainment", hq: "Toronto, Ontario", note: "Owned by Corus Entertainment, TSX: CJR.B — controlled by the Shaw family", confidence: "high",
    alternatives: [] },
  "ctvnews.ca": { brand: "CTV News", ownership: "Canada", category: "Media & Entertainment", hq: "Toronto, Ontario", note: "Owned by Bell Media (BCE Inc.), TSX: BCE", confidence: "high",
    alternatives: [] },

  // ---- Gaming platforms ----
  "store.steampowered.com": { brand: "Steam", ownership: "US", category: "Media & Entertainment", hq: "Bellevue, Washington", note: "Owned by Valve Corporation, privately held US company", confidence: "high",
    alternatives: [] },
  "epicgames.com": { brand: "Epic Games Store", ownership: "US", category: "Media & Entertainment", hq: "Cary, North Carolina", note: "Epic Games, privately held US company", confidence: "high",
    alternatives: [] },
  "playstation.com": { brand: "PlayStation Store", ownership: "not-US", category: "Media & Entertainment", hq: "Tokyo, Japan", note: "Owned by Sony Group Corporation — Japanese, not US-owned. Not Canadian either.", confidence: "high",
    alternatives: [] },
  "xbox.com": { brand: "Xbox / Microsoft Store", ownership: "US", category: "Media & Entertainment", hq: "Redmond, Washington", note: "Owned by Microsoft, NASDAQ: MSFT", confidence: "high",
    alternatives: [] },
  "nintendo.com": { brand: "Nintendo eShop", ownership: "not-US", category: "Media & Entertainment", hq: "Kyoto, Japan", note: "Not US-owned — Japanese company. Not Canadian either.", confidence: "high",
    alternatives: [] },
  "ea.com": { brand: "Electronic Arts (EA)", ownership: "US", category: "Media & Entertainment", hq: "Redwood City, California", note: "NASDAQ: EA. Note: EA owns BioWare, originally a Canadian studio (Edmonton, founded 1995) — the studio still operates in Edmonton but the parent company is US.", confidence: "high",
    alternatives: [] },
  "ubisoft.com": { brand: "Ubisoft", ownership: "not-US", category: "Media & Entertainment", hq: "Saint-Mandé, France", note: "Not US-owned — French company. Not Canadian either. Note: Ubisoft has major Canadian studios (Montreal, Toronto, Quebec City) but the parent company is French.", confidence: "high",
    alternatives: [] },
  "twitch.tv": { brand: "Twitch", ownership: "US", category: "Media & Entertainment", hq: "San Francisco, California", note: "Owned by Amazon, NASDAQ: AMZN", confidence: "high",
    alternatives: [] },
  "discord.com": { brand: "Discord", ownership: "US", category: "Media & Entertainment", hq: "San Francisco, California", note: "Privately held US company", confidence: "high",
    alternatives: [] },
  "roblox.com": { brand: "Roblox", ownership: "US", category: "Media & Entertainment", hq: "San Mateo, California", note: "NYSE: RBLX", confidence: "high",
    alternatives: [] },

  // ---- Reference / high-traffic utility sites ----
  "wikipedia.org": { brand: "Wikipedia", ownership: "US", category: "Tech & Online Services", hq: "San Francisco, California", note: "Operated by the Wikimedia Foundation, a US-based nonprofit — not a for-profit company, but legally US-domiciled. Not Canadian.", confidence: "high",
    alternatives: [] },
  "indeed.com": { brand: "Indeed", ownership: "not-US", category: "Tech & Online Services", hq: "Austin, Texas (US operations) / Tokyo, Japan (Recruit Holdings)", note: "Owned by Recruit Holdings, a Japanese company — not US-owned despite the US operational headquarters. Not Canadian either.", confidence: "high",
    alternatives: [] },
  "linkedin.com": { brand: "LinkedIn", ownership: "US", category: "Tech & Online Services", hq: "Sunnyvale, California", note: "Owned by Microsoft, NASDAQ: MSFT", confidence: "high",
    alternatives: [] },

  // ---- eLearning / instructional design services ----
  "sweetrush.com": { brand: "SweetRush", ownership: "US", category: "Professional Services", hq: "San Francisco, California", note: "Privately held US custom eLearning and instructional design agency", confidence: "high",
    alternatives: ["The Learning Designers (Canadian custom eLearning/instructional design agency)"] },
  "thelearningdesigners.ca": { brand: "The Learning Designers", ownership: "Canada", category: "Professional Services", hq: "Canada", note: "The Learning Designers Incorporated — a custom eLearning design and development / instructional design agency. Confirmed 100% Canadian owned and operated directly by a contractor who works with the company and knows the owner personally — a stronger source than a public registry lookup would be for a small private company.", confidence: "high",
    alternatives: [] },

  // ================= BATCH 2 =================

  // ---- Grocery banners (parent companies already listed above) ----
  "nofrills.ca": { brand: "No Frills", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Brampton, Ontario", note: "Discount banner of Loblaw Companies / George Weston Limited, TSX: L — same Canadian ownership as Loblaws and Shoppers Drug Mart.", confidence: "high",
    alternatives: [] },
  "realcanadiansuperstore.ca": { brand: "Real Canadian Superstore", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Brampton, Ontario", note: "Loblaw Companies banner, TSX: L.", confidence: "high",
    alternatives: [] },
  "tntsupermarket.com": { brand: "T&T Supermarket", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Richmond, British Columbia", note: "Canada's largest Asian grocery chain, founded 1993 by Cindy Lee. Wholly owned by Loblaw Companies (TSX: L) since 2009 — Canadian-owned, though no longer independent.", confidence: "high",
    alternatives: [] },
  "freshco.com": { brand: "FreshCo", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Stellarton, Nova Scotia", note: "Discount banner of Sobeys / Empire Company Ltd., TSX: EMP.A.", confidence: "high",
    alternatives: [] },
  "farmboy.ca": { brand: "Farm Boy", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Ottawa, Ontario", note: "Ottawa-founded fresh grocer, acquired by Sobeys / Empire Company Ltd. (TSX: EMP.A) in 2018 — Canadian ownership before and after the sale.", confidence: "high",
    alternatives: [] },
  "longos.com": { brand: "Longo's", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Vaughan, Ontario", note: "Family-founded Ontario grocer (1956), majority acquired by Sobeys / Empire Company Ltd. in 2021; the Longo family retained a minority stake. Canadian either way.", confidence: "high",
    alternatives: [] },
  "foodbasics.ca": { brand: "Food Basics", ownership: "Canada", category: "Grocery & Pharmacy", hq: "Montreal, Quebec", note: "Discount banner of Metro Inc., TSX: MRU.", confidence: "high",
    alternatives: [] },
  "wholefoodsmarket.com": { brand: "Whole Foods Market", ownership: "US", category: "Grocery & Pharmacy", hq: "Austin, Texas", note: "Owned by Amazon (NASDAQ: AMZN) since the 2017 acquisition.", confidence: "high",
    alternatives: ["Farm Boy (Sobeys-owned, Canadian)", "Save-On-Foods", "local co-ops"] },

  // ---- Retail ----
  "toysrus.ca": { brand: "Toys \"R\" Us Canada", ownership: "Canada", category: "Retail & Department Stores", hq: "Concord, Ontario", note: "The CCAA process finished in June 2026 and split the company three ways: the Toys \"R\" Us Canada and Babies \"R\" Us Canada names and trademarks went to Ad Populum, a US firm; the operating business — ten store leases, inventory, equipment, logistics and bank accounts — went to a company owned by Doug Putman, the existing Canadian owner; and one Vaughan Mills lease went to Fox Group Jumbo Canada. So the stores you can shop at are Canadian-owned, operating a US-owned brand under licence. Still flagged because that licence expires January 25, 2027 and Putman has said he will either extend it or rebrand — this entry needs rechecking then.", confidence: "verify",
    alternatives: ["Mastermind Toys (Canadian-owned)"] },
  "mastermindtoys.com": { brand: "Mastermind Toys", ownership: "Canada", category: "Retail & Department Stores", hq: "Toronto, Ontario", note: "Canadian specialty toy retailer, bought out of CCAA protection in 2023 by an investor group including Joe Mimran (founder of Club Monaco and Joe Fresh) and Frank Rocchetti; Quebec entrepreneur Stephane Tetrault joined as a partner in April 2025. Privately held and Canadian-controlled.", confidence: "high",
    alternatives: [] },
  "princessauto.com": { brand: "Princess Auto", ownership: "Canada", category: "Retail & Department Stores", hq: "Winnipeg, Manitoba", note: "Privately held Canadian retailer, founded in Winnipeg in 1933 and still family-controlled.", confidence: "high",
    alternatives: [] },
  "leevalley.com": { brand: "Lee Valley Tools", ownership: "Canada", category: "Retail & Department Stores", hq: "Ottawa, Ontario", note: "Privately held, family-owned Canadian woodworking and gardening tool retailer, founded in Ottawa in 1978 by Leonard Lee; still run by the Lee family.", confidence: "high",
    alternatives: [] },
  "sunriserecords.com": { brand: "Sunrise Records", ownership: "Canada", category: "Retail & Department Stores", hq: "Ancaster, Ontario", note: "Owned by Doug Putman / Putman Investments, a Canadian family-owned firm. Note the same parent is behind Toys \"R\" Us Canada, which is in CCAA restructuring — worth re-checking this entry periodically.", confidence: "high",
    alternatives: [] },
  "wayfair.ca": { brand: "Wayfair", ownership: "US", category: "Home & Furniture", hq: "Boston, Massachusetts", note: "NYSE: W.", confidence: "high",
    alternatives: ["Structube", "EQ3", "Leon's", "The Brick"] },
  "etsy.com": { brand: "Etsy", ownership: "US", category: "Tech & Online Services", hq: "Brooklyn, New York", note: "NASDAQ: ETSY. Individual sellers on the platform may be Canadian, but the marketplace itself is US-owned.", confidence: "high",
    alternatives: [] },
  "dollartree.com": { brand: "Dollar Tree", ownership: "US", category: "Retail & Department Stores", hq: "Chesapeake, Virginia", note: "NASDAQ: DLTR.", confidence: "high",
    alternatives: ["Dollarama (Canadian, TSX: DOL)", "Giant Tiger"] },
  "temu.com": { brand: "Temu", ownership: "not-US", category: "Tech & Online Services", hq: "Dublin, Ireland (registered) / Shanghai, China (PDD Holdings)", note: "Operated by PDD Holdings, the Chinese company behind Pinduoduo, now domiciled in Ireland. Not US-owned and not Canadian.", confidence: "high",
    alternatives: [] },
  "shein.com": { brand: "Shein", ownership: "not-US", category: "Apparel & Fashion", hq: "Singapore (headquarters) / founded China", note: "Chinese-founded fast fashion company, headquartered in Singapore since 2022. Not US-owned and not Canadian.", confidence: "high",
    alternatives: [] },
  "aliexpress.com": { brand: "AliExpress", ownership: "not-US", category: "Tech & Online Services", hq: "Hangzhou, China", note: "Owned by Alibaba Group (NYSE: BABA is a depositary listing; the company is Chinese). Not US-owned and not Canadian.", confidence: "high",
    alternatives: [] },

  // ---- Apparel ----
  "shopduer.com": { brand: "DUER", ownership: "Canada", category: "Apparel & Fashion", hq: "Vancouver, British Columbia", note: "Privately held Canadian performance denim brand, founded in Vancouver in 2013 by Gary Lenett and Abid Hafeez, who own the business between them. Has taken no outside funding, so ownership has stayed with the founders.", confidence: "high",
    alternatives: [] },
  "oldnavy.ca": { brand: "Old Navy", ownership: "US", category: "Apparel & Fashion", hq: "San Francisco, California", note: "Owned by Gap Inc. (NYSE: GAP), alongside Gap, Banana Republic and Athleta. Widely shopped in Canada but entirely US-owned.", confidence: "high",
    alternatives: ["Ardene (Canadian)", "Roots", "Kotn"] },
  "arcteryx.com": { brand: "Arc'teryx", ownership: "not-US", category: "Apparel & Fashion", hq: "North Vancouver, BC (design and HQ) / Jinjiang, China (Anta Sports)", note: "One of the most commonly assumed-Canadian brands that isn't. Founded in North Vancouver in 1989 and still designed there, but sold to France's Salomon in 2001, then to Finland's Amer Sports in 2005. Since 2019, Amer Sports has been controlled by Anta Sports of China, which led a consortium buyout. Not US-owned, but no longer Canadian-owned despite the Coast Mountains branding.", confidence: "high",
    alternatives: ["Mountain Equipment Company (MEC, Canadian-owned again since 2025)"] },
  "garageclothing.com": { brand: "Garage / Dynamite", ownership: "Canada", category: "Apparel & Fashion", hq: "Montreal, Quebec", note: "Both banners are owned by Groupe Dynamite, a Montreal company founded in 1975 that listed on the TSX (GRGD) in 2024. Canadian-controlled.", confidence: "high",
    alternatives: [] },
  "ardene.com": { brand: "Ardene", ownership: "Canada", category: "Apparel & Fashion", hq: "Montreal, Quebec", note: "Privately held Canadian fashion retailer, founded in Montreal and family-controlled.", confidence: "high",
    alternatives: [] },
  "lavieenrose.com": { brand: "La Vie en Rose", ownership: "Canada", category: "Apparel & Fashion", hq: "Montreal, Quebec", note: "Privately held Canadian lingerie and swimwear retailer, founded in Montreal in 1985 and led by owner Francois Roberge.", confidence: "high",
    alternatives: [] },
  "nike.com": { brand: "Nike", ownership: "US", category: "Apparel & Fashion", hq: "Beaverton, Oregon", note: "NYSE: NKE.", confidence: "high",
    alternatives: ["Sport Chek (Canadian Tire-owned retailer)"], alternativesNote: "No Canadian athletic footwear brand at comparable scale — the closest Canadian option is where you buy, not what you buy." },
  "adidas.ca": { brand: "Adidas", ownership: "not-US", category: "Apparel & Fashion", hq: "Herzogenaurach, Germany", note: "German company (FWB: ADS). Not US-owned, not Canadian.", confidence: "high",
    alternatives: [] },
  "uniqlo.com": { brand: "Uniqlo", ownership: "not-US", category: "Apparel & Fashion", hq: "Tokyo, Japan", note: "Owned by Fast Retailing, a Japanese company. Not US-owned, not Canadian.", confidence: "high",
    alternatives: [] },

  // ---- Personal care ----
  "deciem.com": { brand: "DECIEM / The Ordinary", ownership: "US", category: "Personal Care & Household", hq: "Toronto, Ontario (operations) / New York, New York (Estee Lauder)", note: "Founded in Toronto in 2013 by Brandon Truaxe and still headquartered there with its labs in the city — but no longer Canadian-owned. Estee Lauder (NYSE: EL) invested in 2017, took majority control in 2021, and completed the purchase of the remaining stake on May 31, 2024, making DECIEM wholly US-owned. Confirmed via Estee Lauder's own press release and SEC filings.", confidence: "high",
    alternatives: ["Province Apothecary (Canadian)", "Attitude (Canadian)", "Saje Natural Wellness (Canadian)"] },
  "saje.com": { brand: "Saje Natural Wellness", ownership: "Canada", category: "Personal Care & Household", hq: "Vancouver, British Columbia", note: "Privately held Canadian natural wellness and essential oils retailer, founded in Vancouver in 1992 by Jean-Pierre LeBlanc and Kate Ross LeBlanc, who still own the company.", confidence: "high",
    alternatives: [] },
  "rockymountainsoap.com": { brand: "Rocky Mountain Soap Company", ownership: "Canada", category: "Personal Care & Household", hq: "Canmore, Alberta", note: "Privately held Canadian natural skincare company, founded in Canmore in 2000 and still independently owned; products made in Alberta.", confidence: "high",
    alternatives: [] },
  "bathandbodyworks.com": { brand: "Bath & Body Works", ownership: "US", category: "Personal Care & Household", hq: "Columbus, Ohio", note: "NYSE: BBWI.", confidence: "high",
    alternatives: ["Saje Natural Wellness (Canadian)", "Rocky Mountain Soap Company (Canadian)"] },
  "lush.com": { brand: "Lush", ownership: "not-US", category: "Personal Care & Household", hq: "Poole, United Kingdom", note: "Privately held British company, founded in Poole in 1995 and still owned by its founders and their families. Not US-owned, not Canadian — though Lush does manufacture in Vancouver for the North American market.", confidence: "high",
    alternatives: ["Rocky Mountain Soap Company (Canadian)", "Province Apothecary (Canadian)"] },

  // ---- Food and drink ----
  "skipthedishes.com": { brand: "SkipTheDishes", ownership: "not-US", category: "Food & Drink", hq: "Winnipeg, Manitoba (operations) / Amsterdam, Netherlands (Just Eat Takeaway)", note: "Founded in Saskatoon in 2012 and long headquartered in Winnipeg, but Canadian ownership ended in 2016 when Netherlands-based Just Eat bought it for $200M. Just Eat merged with Takeaway.com (also Dutch) in 2020 to form Just Eat Takeaway. In 2025 Prosus — a Dutch-listed group controlled by South Africa's Naspers — agreed to acquire Just Eat Takeaway, so the parent may change again, but under either owner it is neither US-owned nor Canadian-owned.", confidence: "high",
    alternatives: [], alternativesNote: "Ordering directly from the restaurant, by phone or its own site, keeps the most money with the Canadian business and avoids platform commissions entirely." },
  "laurasecord.ca": { brand: "Laura Secord", ownership: "Canada", category: "Food & Drink", hq: "Quebec City, Quebec", note: "Named for a Canadian War of 1812 heroine, but the company spent decades under foreign ownership (including Archibald Candy of Chicago) before returning to Canadian hands. Now owned by Jean Leclerc's Nutriart of Quebec City. Canadian-owned as of the most recent reporting.", confidence: "high",
    alternatives: [] },
  "purdys.com": { brand: "Purdys Chocolatier", ownership: "Canada", category: "Food & Drink", hq: "Vancouver, British Columbia", note: "Founded in Vancouver in 1907; owned by the Flavelle family since 1963, with Karen Flavelle as sole owner since 1997 and a third generation now involved. Privately held and Canadian.", confidence: "high",
    alternatives: [] },
  "ganong.com": { brand: "Ganong Bros.", ownership: "Canada", category: "Food & Drink", hq: "St. Stephen, New Brunswick", note: "Canada's oldest chocolate company, founded 1873 and still owned and run by the Ganong family — five generations in the same New Brunswick town.", confidence: "high",
    alternatives: [] },
  "agropur.com": { brand: "Agropur", ownership: "Canada", category: "Food & Drink", hq: "Longueuil, Quebec", note: "A dairy cooperative owned by its Canadian farmer members since 1938 — brands include iogo, Natrel and OKA. Cooperative ownership means it cannot be bought by an outside company the way a public dairy could.", confidence: "high",
    alternatives: [] },
  "boosterjuice.com": { brand: "Booster Juice", ownership: "Canada", category: "Food & Drink", hq: "Edmonton, Alberta", note: "Privately held Canadian smoothie and juice franchise, founded in Sherwood Park, Alberta in 1999 and still Canadian-controlled.", confidence: "high",
    alternatives: [] },
  "marybrowns.com": { brand: "Mary Brown's Chicken", ownership: "Canada", category: "Food & Drink", hq: "Markham, Ontario", note: "Canadian fried chicken chain with Newfoundland roots (first store St. John's, 1969), privately held and Canadian-owned.", confidence: "high",
    alternatives: [] },
  "freshii.com": { brand: "Freshii", ownership: "Canada", category: "Food & Drink", hq: "Montreal, Quebec (Foodtastic)", note: "Toronto-founded (2005) fast-casual chain, taken private in 2022 by Foodtastic, the privately held Quebec restaurant group that also owns Second Cup. Canadian-owned.", confidence: "high",
    alternatives: [] },
  "st-hubert.com": { brand: "St-Hubert", ownership: "Canada", category: "Food & Drink", hq: "Vaughan, Ontario", note: "Quebec rotisserie chain founded 1951, acquired by Cara (now Recipe Unlimited) in 2016 and held under Fairfax Financial Holdings (TSX: FFH), a Canadian company.", confidence: "high",
    alternatives: [] },
  "earls.ca": { brand: "Earls Kitchen + Bar", ownership: "Canada", category: "Food & Drink", hq: "Vancouver, British Columbia", note: "Privately held and family-owned by the Fuller family, who founded it in Edmonton in 1982. Operates locations in Canada and the US but ownership is Canadian.", confidence: "high",
    alternatives: [] },
  "whitespot.ca": { brand: "White Spot", ownership: "Canada", category: "Food & Drink", hq: "Vancouver, British Columbia", note: "BC restaurant chain founded 1928, privately held by the Toigo family through Shato Holdings. Canadian-owned.", confidence: "high",
    alternatives: [] },
  "cactusclubcafe.com": { brand: "Cactus Club Cafe", ownership: "Canada", category: "Food & Drink", hq: "Vancouver, British Columbia", note: "Privately held Canadian restaurant group founded in Vancouver in 1988 by Richard Jaffray.", confidence: "high",
    alternatives: [] },
  "subway.com": { brand: "Subway", ownership: "US", category: "Food & Drink", hq: "Shelton, Connecticut / Miami, Florida", note: "Acquired in 2024 by Roark Capital, a US private equity firm that also owns Arby's, Dunkin' and Buffalo Wild Wings.", confidence: "high",
    alternatives: ["Mr. Sub (Canadian-founded)", "local delis"] },
  "dominos.ca": { brand: "Domino's Pizza", ownership: "US", category: "Food & Drink", hq: "Ann Arbor, Michigan", note: "NYSE: DPZ.", confidence: "high",
    alternatives: ["Pizza Pizza (Canadian, TSX: PZA)", "Panago (Canadian)", "Boston Pizza (Canadian)"] },
  "dairyqueen.com": { brand: "Dairy Queen", ownership: "US", category: "Food & Drink", hq: "Bloomington, Minnesota", note: "Owned by Berkshire Hathaway (NYSE: BRK.A), Warren Buffett's US holding company, since 1998.", confidence: "high",
    alternatives: [] },
  "kfc.ca": { brand: "KFC", ownership: "US", category: "Food & Drink", hq: "Louisville, Kentucky", note: "Owned by Yum! Brands (NYSE: YUM), which also owns Taco Bell and Pizza Hut.", confidence: "high",
    alternatives: ["Mary Brown's Chicken (Canadian)"] },

  // ---- Travel ----
  "flyporter.com": { brand: "Porter Airlines", ownership: "Canada", category: "Travel & Transportation", hq: "Toronto, Ontario", note: "Privately held Canadian airline founded in 2006 by Robert Deluce and the Deluce family through REGCO Holdings, with OMERS (the Ontario municipal pension plan) and other institutional investors also holding stakes. Now led by Michael Deluce. Canadian-controlled, as federal airline ownership rules require.", confidence: "high",
    alternatives: [] },
  "fourseasons.com": { brand: "Four Seasons Hotels and Resorts", ownership: "US", category: "Travel & Transportation", hq: "Toronto, Ontario (headquarters)", note: "A case where the head office and the owner are in different countries. Founded in Toronto in 1960 by Isadore Sharp and still headquartered there, but majority ownership is American: Bill Gates' Cascade Investment raised its stake to 71.25% in 2021 by buying half of Kingdom Holding's shares. Saudi Arabia's Kingdom Holding retains about 23.75% and Sharp about 5%. Canadian-run, US-controlled.", confidence: "high",
    alternatives: ["Fairmont properties are Accor-owned (France), also not Canadian — no major Canadian-owned luxury hotel chain remains."] },
  "marriott.com": { brand: "Marriott", ownership: "US", category: "Travel & Transportation", hq: "Bethesda, Maryland", note: "NASDAQ: MAR. Also owns Delta Hotels, a Canadian-founded chain it acquired in 2015.", confidence: "high",
    alternatives: [] },
  "hilton.com": { brand: "Hilton", ownership: "US", category: "Travel & Transportation", hq: "McLean, Virginia", note: "NYSE: HLT.", confidence: "high",
    alternatives: [] },

  // ---- Tech ----
  "blackberry.com": { brand: "BlackBerry", ownership: "Canada", category: "Tech & Online Services", hq: "Waterloo, Ontario", note: "TSX/NYSE: BB — now a cybersecurity and embedded software company rather than a phone maker, but still Canadian-headquartered and incorporated.", confidence: "high",
    alternatives: [] },
  "opentext.com": { brand: "OpenText", ownership: "Canada", category: "Tech & Online Services", hq: "Waterloo, Ontario", note: "TSX/NASDAQ: OTEX — Canada's largest software company, founded at the University of Waterloo in 1991.", confidence: "high",
    alternatives: [] },
  "lightspeedhq.com": { brand: "Lightspeed Commerce", ownership: "Canada", category: "Tech & Online Services", hq: "Montreal, Quebec", note: "TSX/NYSE: LSPD — Canadian point-of-sale and commerce platform founded in Montreal in 2005.", confidence: "high",
    alternatives: [] },
  "csisoftware.com": { brand: "Constellation Software", ownership: "Canada", category: "Tech & Online Services", hq: "Toronto, Ontario", note: "TSX: CSU — one of Canada's largest public companies, acquiring and operating vertical market software businesses worldwide.", confidence: "high",
    alternatives: [] },
  "nuvei.com": { brand: "Nuvei", ownership: "verify", category: "Tech & Online Services", hq: "Montreal, Quebec", note: "Checked, and the answer depends on which measure you use — this flag is the finding. Nuvei was taken private in November 2024 in a transaction led by Advent International, a US private equity firm, so control sits in the US. But the Canadian shareholders who rolled over hold more of the equity between them: founder-CEO Philip Fayer at roughly 24%, Novacap at about 18% and the Caisse de depot et placement du Quebec at about 12%, with Fayer still leading the company from Montreal. Control says American, shareholding says Canadian.", confidence: "verify",
    alternatives: [] },
  "wealthsimple.com": { brand: "Wealthsimple", ownership: "Canada", category: "Banking & Insurance", hq: "Toronto, Ontario", note: "Majority-owned by Power Corporation of Canada (TSX: POW) through its affiliates — a Montreal-based Canadian holding company.", confidence: "high",
    alternatives: [] },
  "tiktok.com": { brand: "TikTok", ownership: "not-US", category: "Media & Entertainment", hq: "Singapore / Los Angeles (operations) / Beijing, China (ByteDance)", note: "Resolved, with a geographic split that matters here. In January 2026 TikTok's US business was carved into a separate entity, TikTok USDS Joint Venture LLC, 80.1% held by US and global investors (Oracle, Silver Lake and Abu Dhabi's MGX at about 15% each) with ByteDance retaining 19.9%. That restructuring covers the United States only. Canadian users are served by TikTok's global business, which remains ByteDance-controlled. So from Canada this is a Chinese-owned service — not US-owned, and not Canadian.", confidence: "high",
    alternatives: [] },
  "reddit.com": { brand: "Reddit", ownership: "US", category: "Media & Entertainment", hq: "San Francisco, California", note: "NYSE: RDDT since its 2024 IPO; Advance Publications remains the largest shareholder.", confidence: "high",
    alternatives: [] },

  // ---- Telecom ----
  "videotron.com": { brand: "Videotron", ownership: "Canada", category: "Telecom & Mobile", hq: "Montreal, Quebec", note: "Subsidiary of Quebecor (TSX: QBR.B), a Quebec company controlled by the Peladeau family. Also owns Freedom Mobile.", confidence: "high",
    alternatives: [] },
  "eastlink.ca": { brand: "Eastlink", ownership: "Canada", category: "Telecom & Mobile", hq: "Halifax, Nova Scotia", note: "Privately held by Bragg Communications, a Nova Scotia family company — one of the few remaining independent Canadian telecom operators.", confidence: "high",
    alternatives: [] },
  "sasktel.com": { brand: "SaskTel", ownership: "Canada", category: "Telecom & Mobile", hq: "Regina, Saskatchewan", note: "A Crown corporation owned by the Government of Saskatchewan — publicly owned by the province rather than by shareholders.", confidence: "high",
    alternatives: [] },

  // ---- Banking ----
  "tangerine.ca": { brand: "Tangerine", ownership: "Canada", category: "Banking & Insurance", hq: "Toronto, Ontario", note: "Owned by Scotiabank (TSX: BNS) since 2012, when it was bought from ING Group and rebranded from ING Direct Canada.", confidence: "high",
    alternatives: [] },
  "simplii.com": { brand: "Simplii Financial", ownership: "Canada", category: "Banking & Insurance", hq: "Toronto, Ontario", note: "Direct banking brand of CIBC (TSX: CM), launched in 2017 after CIBC's partnership with Loblaw's PC Financial ended.", confidence: "high",
    alternatives: [] },
  "eqbank.ca": { brand: "EQ Bank", ownership: "Canada", category: "Banking & Insurance", hq: "Toronto, Ontario", note: "Digital banking arm of Equitable Bank, TSX: EQB — a Canadian-owned schedule I bank.", confidence: "high",
    alternatives: [] },
  "questrade.com": { brand: "Questrade", ownership: "Canada", category: "Banking & Insurance", hq: "Toronto, Ontario", note: "Privately held Canadian online brokerage, founded in Toronto in 1999 by Edward Kholodenko, who still leads it.", confidence: "high",
    alternatives: [] },

  // ---- Gas ----
  "parkland.ca": { brand: "Parkland (On the Run, Ultramar, Chevron Canada sites)", ownership: "Canada", category: "Gas & Convenience", hq: "Calgary, Alberta", note: "TSX: PKI — Canadian fuel retailer operating the Ultramar, Pioneer, Fas Gas and On the Run banners, and licensing the Chevron brand for its BC stations. Canadian-headquartered and listed.", confidence: "high",
    alternatives: [] },
  "chevron.com": { brand: "Chevron", ownership: "US", category: "Gas & Convenience", hq: "Houston, Texas", note: "NYSE: CVX. Note: many Chevron-branded stations in British Columbia are operated by Parkland, a Canadian company, under licence — the brand is US but the local operator may not be.", confidence: "high",
    alternatives: ["Petro-Canada", "Parkland-operated stations (Ultramar, Pioneer, Fas Gas)"] },

  // ---- Media ----
  "thestar.com": { brand: "Toronto Star", ownership: "Canada", category: "Media & Entertainment", hq: "Toronto, Ontario", note: "Owned by NordStar Capital, a Canadian private investment firm led by Jordan Bitove, which bought Torstar in 2020. Canadian-owned — unlike the National Post, whose parent Postmedia is majority-owned by a US hedge fund.", confidence: "high",
    alternatives: [] },
  "tsn.ca": { brand: "TSN", ownership: "Canada", category: "Media & Entertainment", hq: "Toronto, Ontario", note: "Owned by Bell Media (BCE Inc., TSX: BCE).", confidence: "high",
    alternatives: [] },
  "sportsnet.ca": { brand: "Sportsnet", ownership: "Canada", category: "Media & Entertainment", hq: "Toronto, Ontario", note: "Owned by Rogers Communications (TSX: RCI.B).", confidence: "high",
    alternatives: [] },
  "tv.apple.com": { brand: "Apple TV+", ownership: "US", category: "Media & Entertainment", hq: "Cupertino, California", note: "Owned by Apple (NASDAQ: AAPL).", confidence: "high",
    alternatives: ["CBC Gem", "Crave"] },


  // ---- Men's basics ----
  "saxxunderwear.com": { brand: "SAXX Underwear", ownership: "US", category: "Apparel & Fashion", hq: "Vancouver, British Columbia (headquarters and design) / New York, New York (TZP Group)", note: "Founded in Vancouver in 2006 by Trent Kitsch and still headquartered and designed there, but control passed to US private equity in August 2021, when New York's TZP Group invested through TZP Capital Partners III. The announcement stated that Vancouver's Krystal Growth Partners, via NLS Group Holdings, retained a 'significant minority interest' — minority being the operative word — and independent trade press reported the transaction as TZP acquiring control. Brentwood Associates, a US firm invested since 2016, exited in the same deal. Kept flagged only because Krystal's own portfolio page still describes the pre-2021 structure and lists Brentwood as a current shareholder, which the transaction announcement contradicts; that page reads as stale rather than as a competing account. A direct statement from SAXX would close this.", confidence: "verify",
    alternatives: ["Manmade (Canadian, Montreal)", "Kotn (Canadian)"] },
  "manmadebrand.com": { brand: "Manmade", ownership: "Canada", category: "Apparel & Fashion", hq: "Montreal, Quebec", note: "Privately held Canadian men's basics brand — boxer briefs, socks and tees — founded in Montreal in 2021 by four friends who met at Concordia University and still run it. No outside acquisition; independent and Canadian-owned. Confirmed via Concordia University's own profile of the founders plus independent Canadian retail coverage.", confidence: "high",
    alternatives: [] },


  // ---- Dating & Social ----
  // Note on this category: the online dating market is unusually concentrated.
  // Match Group alone owns Tinder, Hinge, Match, OkCupid and Plenty of Fish,
  // so several "different" apps are the same US company. There is no
  // Canadian-owned dating app at national scale — Plenty of Fish was the one,
  // and it was sold to Match in 2015.
  "pof.com": { brand: "Plenty of Fish", ownership: "US", category: "Dating & Social", hq: "Vancouver, BC (operations) / Dallas, Texas (Match Group)", note: "The clearest case of a Canadian dating company that stopped being Canadian. Founded in Vancouver in 2003 by Markus Frind and famously run as a near-solo operation, it was sold to Match Group in 2015 for US$575M in cash — a sale that required federal industry minister approval under the Investment Canada Act. Still operates from Vancouver, but owned by Match Group (NASDAQ: MTCH) of Dallas.", confidence: "high",
    alternatives: [], alternativesNote: "No Canadian-owned dating app operates at comparable scale — Plenty of Fish was that app before the 2015 sale. Ruby (Toronto) is the main Canadian-owned operator left, but its brands are niche rather than general-purpose." },
  "tinder.com": { brand: "Tinder", ownership: "US", category: "Dating & Social", hq: "West Hollywood, California / Dallas, Texas (Match Group)", note: "Owned by Match Group, NASDAQ: MTCH.", confidence: "high",
    alternatives: [], alternativesNote: "Hinge, Match, OkCupid and Plenty of Fish are all owned by the same company (Match Group), so switching between them does not change who gets paid." },
  "hinge.co": { brand: "Hinge", ownership: "US", category: "Dating & Social", hq: "New York, New York", note: "Owned by Match Group (NASDAQ: MTCH), which took full ownership in 2019 — the same parent as Tinder, Match, OkCupid and Plenty of Fish.", confidence: "high",
    alternatives: [] },
  "match.com": { brand: "Match", ownership: "US", category: "Dating & Social", hq: "Dallas, Texas", note: "The namesake brand of Match Group, NASDAQ: MTCH.", confidence: "high",
    alternatives: [] },
  "okcupid.com": { brand: "OkCupid", ownership: "US", category: "Dating & Social", hq: "New York, New York", note: "Owned by Match Group (NASDAQ: MTCH) since 2011.", confidence: "high",
    alternatives: [] },
  "bumble.com": { brand: "Bumble", ownership: "US", category: "Dating & Social", hq: "Austin, Texas", note: "Bumble Inc., NASDAQ: BMBL. Also owns Badoo and Fruitz. The main scale competitor to Match Group, but equally American.", confidence: "high",
    alternatives: [] },
  "badoo.com": { brand: "Badoo", ownership: "US", category: "Dating & Social", hq: "London, UK (operations) / Austin, Texas (Bumble Inc.)", note: "Founded in Russia in 2006 and long run from London, but consolidated under US-listed Bumble Inc. (NASDAQ: BMBL) in its 2020 corporate restructuring.", confidence: "high",
    alternatives: [] },
  "grindr.com": { brand: "Grindr", ownership: "US", category: "Dating & Social", hq: "West Hollywood, California", note: "Notable ownership history: Chinese gaming company Beijing Kunlun Tech bought Grindr in 2016-2018, then was ordered by CFIUS, the US foreign-investment security committee, to divest it on national security grounds because the app held users' location, messages and HIV status. Kunlun sold to US-based San Vicente Acquisition Partners in 2020 for about US$608M. Grindr went public in 2022 and trades as NYSE: GRND.", confidence: "high",
    alternatives: [] },
  "ashleymadison.com": { brand: "Ashley Madison", ownership: "Canada", category: "Dating & Social", hq: "Toronto, Ontario", note: "Canadian-owned, which surprises people who assume otherwise. Operated by Ruby Life Inc. (the company formerly called Avid Life Media, renamed Ruby in 2016), a privately held Toronto company that also runs Cougar Life. Listed here as an ownership fact, not an endorsement — the 2015 data breach and the resulting FTC and class-action settlements are part of this company's record.", confidence: "high",
    alternatives: [] },
  "cougarlife.com": { brand: "Cougar Life", ownership: "Canada", category: "Dating & Social", hq: "Toronto, Ontario", note: "Operated by Ruby Life Inc. of Toronto, the same privately held Canadian company behind Ashley Madison.", confidence: "high",
    alternatives: [] },
  "eharmony.com": { brand: "eharmony", ownership: "not-US", category: "Dating & Social", hq: "Los Angeles, California (operations) / Hamburg, Germany (ParshipMeet Group)", note: "Founded in California in 2000 but no longer American-controlled. Acquired in 2018 by Germany's ProSiebenSat.1 through its NuCom/Parship arm, and now held by ParshipMeet Group, roughly 55% ProSiebenSat.1 and 45% General Atlantic (a US private equity firm) — so a substantial US minority sits under a European majority. As of December 2025, ProSiebenSat.1 itself is about 75.6% controlled by Italy's MFE-MediaForEurope, adding another layer above it. Not US-controlled and not Canadian.", confidence: "high",
    alternatives: [] },
  "zoosk.com": { brand: "Zoosk", ownership: "verify", category: "Dating & Social", hq: "Berlin, Germany (Spark Networks)", note: "Checked and still genuinely unresolved — the insolvency has not concluded. Spark Networks Services GmbH, which owns Zoosk along with Christian Mingle, JDate, JSwipe, EliteSingles and SilverSingles, was placed under preliminary insolvency administration by a Berlin court in January 2026 after its US lender and equity holder MGG Investment Group withdrew funding, and filed Chapter 15 in the US to have those proceedings recognised. The administrator intends to sell the assets while the sites keep running, but as of the most recent reporting no buyer has been confirmed. Whoever ends up owning these brands is still being decided.", confidence: "verify",
    alternatives: [] },
  "christianmingle.com": { brand: "Christian Mingle", ownership: "verify", category: "Dating & Social", hq: "Berlin, Germany (Spark Networks)", note: "Same unresolved insolvency as Zoosk — a Spark Networks Services GmbH brand. Berlin insolvency administration opened January 2026, Chapter 15 recognition filed in the US, an asset sale intended but no buyer confirmed as of the most recent reporting.", confidence: "verify",
    alternatives: [] },
  "jdate.com": { brand: "JDate", ownership: "verify", category: "Dating & Social", hq: "Berlin, Germany (Spark Networks)", note: "Same unresolved insolvency as Zoosk and Christian Mingle — a Spark Networks Services GmbH brand. Berlin insolvency administration opened January 2026, Chapter 15 recognition filed in the US, an asset sale intended but no buyer confirmed as of the most recent reporting.", confidence: "verify",
    alternatives: [] },
  "happn.com": { brand: "happn", ownership: "not-US", category: "Dating & Social", hq: "Paris, France", note: "Privately held French company, founded in Paris in 2014. Not US-owned, not Canadian.", confidence: "high",
    alternatives: [] },
  "feeld.co": { brand: "Feeld", ownership: "not-US", category: "Dating & Social", hq: "London, United Kingdom", note: "Privately held British company, founded in London in 2014. Not US-owned, not Canadian.", confidence: "high",
    alternatives: [] },
  "coffeemeetsbagel.com": { brand: "Coffee Meets Bagel", ownership: "US", category: "Dating & Social", hq: "San Francisco, California", note: "Privately held US company, founded in 2012 by the Kang sisters.", confidence: "high",
    alternatives: [] },


  // ---- Independent Canadian clothing labels ----
  // Ownership and manufacturing are different questions, and this group is
  // unusual in satisfying both: each is Canadian-owned AND cuts and sews in
  // Canada, which most of the apparel entries above do not.
  "franklyman.com": { brand: "Frank Lyman Design", ownership: "Canada", category: "Apparel & Fashion", hq: "Montreal, Quebec", note: "Privately held family business, founded in Montreal in 2001 by Frank Lyman after 25 years at Joseph Ribkoff. His daughter Stephanie became president in 2016 and two of his sons work in the business. Around 98% of the line is manufactured in Canada by subcontractors, and it sells into thousands of stores in dozens of countries — a Canadian-owned exporter rather than a domestic-only label.", confidence: "high",
    alternatives: [] },
  "encircled.ca": { brand: "Encircled", ownership: "Canada", category: "Apparel & Fashion", hq: "Toronto, Ontario", note: "Founded in Toronto in 2012 by Kristi Soomer, who still owns and runs it as CEO. Everything is made in Toronto and more than half the fabric is knit in Canada. A Certified B Corporation, which is a third-party audited standard rather than a self-declared one.", confidence: "high",
    alternatives: [] },
  "freelabel.com": { brand: "Free Label", ownership: "Canada", category: "Apparel & Fashion", hq: "Vancouver, British Columbia", note: "Founded in 2015 by Jess Sternberg, who started the label precisely because she could not find Canadian-made clothing she wanted to wear. Based in Vancouver since 2016 and run with her husband Julian Hoyle; garments are cut and sewn in Toronto and Vancouver, with much of the fabric custom milled in Toronto. Independently owned — no outside acquisition.", confidence: "high",
    alternatives: [] },
  "provinceofcanada.com": { brand: "Province of Canada", ownership: "Canada", category: "Apparel & Fashion", hq: "Toronto, Ontario", note: "Independent Toronto label founded by Julie and Jeremy, built on the rule that every product is made in Canada — knit and sewn in Toronto, with materials sourced domestically wherever possible rather than outsourced. Privately held.", confidence: "high",
    alternatives: [] },
  "birdsofnorthamerica.com": { brand: "Birds of North America", ownership: "Canada", category: "Apparel & Fashion", hq: "Toronto, Ontario", note: "Founded in 2007 by designer Hayley Gibson, starting in a Victoria BC studio, then Montreal, and in Toronto's Junction Triangle since 2015 where design and pattern-making happen. Every garment has been made in Canada since the label began. The West Queen West storefront closed in January 2024 and the business moved fully online — still operating, still independently owned.", confidence: "high",
    alternatives: [] },
  "elizafaulkner.com": { brand: "Eliza Faulkner", ownership: "Canada", category: "Apparel & Fashion", hq: "Montreal, Quebec", note: "Eliza Faulkner Designs Inc., the namesake label launched in 2012 by the Central Saint Martins-trained designer after working at Erdem, Roland Mouret and Zandra Rhodes in London. Designed and produced in Montreal, with deadstock fabric used where possible. Independently owned; a two-time Canadian Arts and Fashion Awards nominee.", confidence: "high",
    alternatives: [] },
  "jerico.ca": { brand: "JERICO", ownership: "Canada", category: "Apparel & Fashion", hq: "Greater Toronto Area, Ontario", note: "Family-owned since 1987, started by two brothers and two sisters, making basics — t-shirts, sweatshirts, sweatpants, hoodies — entirely in Canada. It kept domestic production after import quotas were lifted in 2001, which is when most of the Canadian garment industry moved offshore; that decision is why it is one of the few remaining Canadian-made basics manufacturers.", confidence: "high",
    alternatives: [] },
  "goodforsunday.com": { brand: "Good For Sunday", ownership: "Canada", category: "Apparel & Fashion", hq: "Toronto, Ontario", note: "Toronto-based independent label making loungewear and everyday basics, designed and manufactured in Canada. Also runs a Canadian private-label and wholesale manufacturing arm, so it produces domestically for other brands as well as its own.", confidence: "high",
    alternatives: [] },

};

// Simple lookup by hostname
function lookupDomain(hostname) {
  const clean = hostname.replace(/^www\./, "");
  return OWNERSHIP_DATA[clean] || null;
}
