// MapleCheck ownership database — STARTER BATCH v0.1
// IMPORTANT: This is a first-pass dataset built from well-established public
// facts (stock exchange listings, headquarters locations). It has NOT been
// through a legal/verification pass. Do not publish or make public claims
// from this file until each entry has been checked and sourced properly —
// see /areas/buy-canadian-extension.md notes on liability risk.
//
// confidence: "high" = widely known, uncontested public fact (HQ, stock listing)
// confidence: "verify" = needs a dedicated source check before launch

const OWNERSHIP_DATA = {
  // ---- US-owned / US-headquartered ----
  "walmart.ca": { brand: "Walmart", ownership: "US", hq: "Bentonville, Arkansas", note: "NYSE: WMT", confidence: "high",
    alternatives: ["Loblaws / Real Canadian Superstore", "Sobeys", "Giant Tiger"] },
  "amazon.ca": { brand: "Amazon", ownership: "US", hq: "Seattle, Washington", note: "NASDAQ: AMZN", confidence: "high",
    alternatives: ["Well.ca", "Indigo.ca", "local retailers"] },
  "costco.ca": { brand: "Costco", ownership: "US", hq: "Issaquah, Washington", note: "NASDAQ: COST", confidence: "high",
    alternatives: ["Wholesale Club (Federated Co-op)", "Loblaws"] },
  "homedepot.ca": { brand: "Home Depot", ownership: "US", hq: "Atlanta, Georgia", note: "NYSE: HD", confidence: "high",
    alternatives: ["Canadian Tire", "Home Hardware"] },
  "target.com": { brand: "Target", ownership: "US", hq: "Minneapolis, Minnesota", note: "NYSE: TGT — no longer operates stores in Canada but ships to CA", confidence: "high",
    alternatives: ["Canadian Tire", "Winners"] },
  "bestbuy.ca": { brand: "Best Buy", ownership: "US", hq: "Richfield, Minnesota", note: "NYSE: BBY", confidence: "high",
    alternatives: ["Canada Computers", "Memory Express"] },
  "starbucks.ca": { brand: "Starbucks", ownership: "US", hq: "Seattle, Washington", note: "NASDAQ: SBUX", confidence: "high",
    alternatives: ["Tim Hortons", "Second Cup", "local roasters"] },
  "mcdonalds.com": { brand: "McDonald's", ownership: "US", hq: "Chicago, Illinois", note: "NYSE: MCD", confidence: "high",
    alternatives: ["Tim Hortons", "A&W Canada (majority Canadian-owned)"] },
  "netflix.com": { brand: "Netflix", ownership: "US", hq: "Los Gatos, California", note: "NASDAQ: NFLX", confidence: "high",
    alternatives: ["CBC Gem", "Crave"] },
  "rona.ca": { brand: "Rona", ownership: "US", hq: "Boucherville, QC (operations) — owned by Sycamore Partners, New York", note: "Sold by Lowe's to US private equity firm Sycamore Partners in Feb 2023. Despite Canadian branding/history and 'Truly Canadian' marketing, current ownership is US private equity. Source: Lowe's/Sycamore Partners deal announcements, Nov 2022–Feb 2023.", confidence: "high",
    alternatives: ["Canadian Tire", "Home Hardware"] },
  "staples.ca": { brand: "Staples Canada", ownership: "US", hq: "Richmond Hill, ON (operations) — owned by Sycamore Partners, New York", note: "Same US private equity owner as Rona (Sycamore Partners)", confidence: "high",
    alternatives: ["Grand & Toy", "local office suppliers"] },
  "apple.com": { brand: "Apple", ownership: "US", hq: "Cupertino, California", note: "NASDAQ: AAPL", confidence: "high",
    alternatives: [], otherAlternatives: ["Samsung (South Korea)"], alternativesNote: "No Canadian phone/OS maker exists. Samsung isn't Canadian either, but it's not US-owned — listed as a non-US option, not a Canadian one." },
  "google.com": { brand: "Google", ownership: "US", hq: "Mountain View, California", note: "NASDAQ: GOOGL (Alphabet)", confidence: "high",
    alternatives: [], otherAlternatives: ["Ecosia (Germany)", "Qwant (France)"], alternativesNote: "No Canadian search engine at scale. DuckDuckGo is often suggested but is also US-owned (Pennsylvania) — excluded for that reason. Ecosia/Qwant are non-US, not Canadian." },
  "microsoft.com": { brand: "Microsoft", ownership: "US", hq: "Redmond, Washington", note: "NASDAQ: MSFT", confidence: "high",
    alternatives: [], otherAlternatives: ["LibreOffice (open-source, EU-based nonprofit)"], alternativesNote: "No Canadian OS/productivity suite at scale. LibreOffice isn't Canadian but isn't a US corporation either." },
  "uber.com": { brand: "Uber", ownership: "US", hq: "San Francisco, California", note: "NYSE: UBER", confidence: "high",
    alternatives: ["local taxi apps"] },
  "winners.ca": { brand: "Winners / Marshalls / HomeSense", ownership: "US", hq: "Framingham, Massachusetts", note: "Owned by TJX Companies, NYSE: TJX", confidence: "high",
    alternatives: [] },
  "ikea.com": { brand: "IKEA", ownership: "not-US", hq: "Leiden, Netherlands (Inter IKEA) / founded Sweden", note: "Not US-owned — the Inter IKEA/Netherlands foundation structure is well-documented, publicly established fact, not a disputed or unclear case. Not Canadian either.", confidence: "high",
    alternatives: [] },

  // ---- Canadian-owned ----
  "loblaws.ca": { brand: "Loblaws", ownership: "Canada", hq: "Brampton, Ontario", note: "Owned by George Weston Limited / Weston family, TSX: L", confidence: "high",
    alternatives: [] },
  "canadiantire.ca": { brand: "Canadian Tire", ownership: "Canada", hq: "Toronto, Ontario", note: "TSX: CTC", confidence: "high",
    alternatives: [] },
  "timhortons.ca": { brand: "Tim Hortons", ownership: "verify", hq: "Oakville, Ontario (brand HQ)", note: "Genuinely mixed, not a clean flag. The brand is Canadian and run as a distinct Canadian business, but the parent company, Restaurant Brands International (RBI), also owns Burger King (US) and was formed via 2014 merger backed by 3G Capital (Brazil). 3G's stake has fallen from ~51% (2014) to ~26% (most recent reporting); Canadian institutional investors (TD, BMO, RBC, CPP Investment Board) now hold a comparable combined stake. RBI is dual-listed NYSE/TSX, HQ Toronto. No single country cleanly owns it today.", confidence: "verify",
    alternatives: [] },
  "sobeys.com": { brand: "Sobeys", ownership: "Canada", hq: "Stellarton, Nova Scotia", note: "Owned by Empire Company Ltd., TSX: EMP.A", confidence: "high",
    alternatives: [] },
  "mec.ca": { brand: "Mountain Equipment Company (MEC)", ownership: "Canada", hq: "Vancouver, BC", note: "Sold back to a Canadian investor group led by Tim Gu (also an investor in Roots and Tilley) in May 2025, ending the 2020–2025 period of US private equity ownership under Kingswood Capital Management. Confirmed via MEC's own press release plus independent retail trade reporting (retail-insider.com, hardlines.ca). A partial management buyout — CEO Peter Hlynsky and CMO Chris Speyer are also part of the new ownership group.", confidence: "high",
    alternatives: [] },
  "indigo.ca": { brand: "Indigo", ownership: "Canada", hq: "Toronto, Ontario", note: "TSX: IDG", confidence: "high",
    alternatives: [] },
  "well.ca": { brand: "Well.ca", ownership: "Canada", hq: "Ontario", note: "Owned by Birch Hill Equity Partners (Canadian PE firm) since Dec 2024, after being owned by US-based McKesson 2016–2024. Source: McKesson divestiture announcement, Dec 30 2024.", confidence: "high",
    alternatives: [] },
  "rexall.ca": { brand: "Rexall", ownership: "Canada", hq: "Mississauga, Ontario", note: "Owned by Birch Hill Equity Partners (Canadian PE firm) since Dec 2024, after being owned by US-based McKesson 2016–2024. Same ownership history as Well.ca.", confidence: "high",
    alternatives: [] },
  "bell.ca": { brand: "Bell Canada", ownership: "Canada", hq: "Verdun, Quebec", note: "Owned by BCE Inc., TSX: BCE", confidence: "high",
    alternatives: [] },
  "rogers.com": { brand: "Rogers", ownership: "Canada", hq: "Toronto, Ontario", note: "TSX: RCI.B — Rogers family control", confidence: "high",
    alternatives: [] },
  "telus.com": { brand: "Telus", ownership: "Canada", hq: "Vancouver, BC", note: "TSX: T", confidence: "high",
    alternatives: [] },
  "rbc.com": { brand: "RBC (Royal Bank of Canada)", ownership: "Canada", hq: "Toronto, Ontario", note: "TSX: RY", confidence: "high",
    alternatives: [] },
  "td.com": { brand: "TD Bank", ownership: "Canada", hq: "Toronto, Ontario", note: "TSX: TD — note: TD also operates US retail banking (TD Bank, N.A.) as a subsidiary, but the parent company is Canadian", confidence: "high",
    alternatives: [] },
  "scotiabank.com": { brand: "Scotiabank", ownership: "Canada", hq: "Toronto, Ontario", note: "TSX: BNS", confidence: "high",
    alternatives: [] },
  "bmo.com": { brand: "BMO (Bank of Montreal)", ownership: "Canada", hq: "Montreal / Toronto", note: "TSX: BMO", confidence: "high",
    alternatives: [] },
  "cibc.com": { brand: "CIBC", ownership: "Canada", hq: "Toronto, Ontario", note: "TSX: CM", confidence: "high",
    alternatives: [] },
  "shoppersdrugmart.ca": { brand: "Shoppers Drug Mart", ownership: "Canada", hq: "Toronto, Ontario", note: "Owned by Loblaw Companies / George Weston Limited", confidence: "high",
    alternatives: [] },
  "metro.ca": { brand: "Metro", ownership: "Canada", hq: "Montreal, Quebec", note: "TSX: MRU", confidence: "high",
    alternatives: [] },
  "dollarama.com": { brand: "Dollarama", ownership: "Canada", hq: "Montreal, Quebec", note: "TSX: DOL", confidence: "high",
    alternatives: [] },
  "shopify.com": { brand: "Shopify", ownership: "Canada", hq: "Ottawa, Ontario", note: "TSX/NYSE: SHOP — founded and headquartered in Canada", confidence: "high",
    alternatives: [] },
  "aircanada.com": { brand: "Air Canada", ownership: "Canada", hq: "Montreal, Quebec", note: "TSX: AC", confidence: "high",
    alternatives: [] },
  "westjet.com": { brand: "WestJet", ownership: "Canada", hq: "Calgary, Alberta", note: "Owned by Onex Corporation, a Canadian private equity firm, since 2019", confidence: "high",
    alternatives: [] },
  "homehardware.ca": { brand: "Home Hardware", ownership: "Canada", hq: "St. Jacobs, Ontario", note: "Independently, privately Canadian-owned dealer cooperative", confidence: "high",
    alternatives: [] },
  "lululemon.com": { brand: "Lululemon", ownership: "verify", hq: "Vancouver, BC (HQ) / incorporated in Delaware, US", note: "Genuinely mixed case: founded and headquartered in Vancouver, but incorporated in the US and listed on NASDAQ. Founder Chip Wilson holds ~8.4%; largest shareholders are US institutional funds (FMR, Vanguard, BlackRock). Needs a nuanced explainer, not a simple US/Canada flag.", confidence: "verify",
    alternatives: [] },
  "aritzia.com": { brand: "Aritzia", ownership: "Canada", hq: "Vancouver, BC", note: "TSX: ATZ", confidence: "high",
    alternatives: [] },
  "canadagoose.com": { brand: "Canada Goose", ownership: "Canada", hq: "Toronto, Ontario", note: "TSX/NYSE: GOOS — dual-listed but Canadian headquartered and founded", confidence: "high",
    alternatives: [] },
  "roots.com": { brand: "Roots", ownership: "Canada", hq: "Toronto, Ontario", note: "TSX: ROOT", confidence: "high",
    alternatives: [] },
  "spotify.com": { brand: "Spotify", ownership: "not-US", hq: "Stockholm, Sweden", note: "Not US-owned — Swedish company, NYSE listing is just where it trades, not where it's owned/controlled", confidence: "high",
    alternatives: ["CBC Music"] },
  "sportchek.ca": { brand: "Sport Chek", ownership: "Canada", hq: "Toronto, Ontario", note: "Owned by Canadian Tire Corporation, TSX: CTC", confidence: "high",
    alternatives: [] },
  "marks.com": { brand: "Mark's", ownership: "Canada", hq: "Calgary, Alberta", note: "Owned by Canadian Tire Corporation, TSX: CTC", confidence: "high",
    alternatives: [] },
  "saveonfoods.com": { brand: "Save-On-Foods", ownership: "Canada", hq: "Langley, BC", note: "Owned by Jim Pattison Group, a privately held Canadian conglomerate", confidence: "high",
    alternatives: [] },
  "iga.net": { brand: "IGA (Quebec)", ownership: "Canada", hq: "Montreal, Quebec", note: "Quebec banner of Sobeys, owned by Empire Company Ltd.", confidence: "high",
    alternatives: [] },
  "gianttiger.com": { brand: "Giant Tiger", ownership: "Canada", hq: "Ottawa, Ontario", note: "Privately held, Canadian-owned since 1961", confidence: "high",
    alternatives: [] },
  "londondrugs.com": { brand: "London Drugs", ownership: "Canada", hq: "Richmond, BC", note: "Privately held, Canadian-owned", confidence: "high",
    alternatives: [] },
  "doordash.com": { brand: "DoorDash", ownership: "US", hq: "San Francisco, California", note: "NASDAQ: DASH", confidence: "high",
    alternatives: ["local delivery services"] },
  "disneyplus.com": { brand: "Disney+", ownership: "US", hq: "Burbank, California", note: "NYSE: DIS", confidence: "high",
    alternatives: ["CBC Gem", "Crave"] },
  "hulu.com": { brand: "Hulu", ownership: "US", hq: "Santa Monica, California", note: "Owned by The Walt Disney Company, NYSE: DIS", confidence: "high",
    alternatives: ["CBC Gem", "Crave"] },
  "primevideo.com": { brand: "Amazon Prime Video", ownership: "US", hq: "Seattle, Washington", note: "NASDAQ: AMZN", confidence: "high",
    alternatives: ["CBC Gem", "Crave"] },
  "airbnb.com": { brand: "Airbnb", ownership: "US", hq: "San Francisco, California", note: "NASDAQ: ABNB", confidence: "high",
    alternatives: [] },
  "expedia.ca": { brand: "Expedia", ownership: "US", hq: "Seattle, Washington", note: "NASDAQ: EXPE", confidence: "high",
    alternatives: ["FlightHub (Canadian)", "Air Canada Vacations"] },

  // ---- Canadian-owned ----
  "crave.ca": { brand: "Crave", ownership: "Canada", hq: "Toronto, Ontario", note: "Owned by Bell Media (BCE Inc.), the largest Canadian-owned streaming service", confidence: "high",
    alternatives: [] },
  "cbc.ca": { brand: "CBC / CBC Gem", ownership: "Canada", hq: "Toronto, Ontario", note: "Crown corporation, publicly owned by the Government of Canada", confidence: "high",
    alternatives: [] },
  "manulife.ca": { brand: "Manulife", ownership: "Canada", hq: "Toronto, Ontario", note: "TSX: MFC", confidence: "high",
    alternatives: [] },
  "sunlife.ca": { brand: "Sun Life", ownership: "Canada", hq: "Toronto, Ontario", note: "TSX: SLF", confidence: "high",
    alternatives: [] },
  "desjardins.com": { brand: "Desjardins", ownership: "Canada", hq: "Levis, Quebec", note: "Cooperative financial group, member-owned, largest credit union in Canada", confidence: "high",
    alternatives: [] },
  "flighthub.com": { brand: "FlightHub", ownership: "Canada", hq: "Montreal, Quebec", note: "Subsidiary of Momentum Ventures, co-founded by Matt Keezer. Confirmed Canadian via multiple independent business profiles and the company's own press materials.", confidence: "high",
    alternatives: [] },
  "petro-canada.ca": { brand: "Petro-Canada", ownership: "Canada", hq: "Calgary, Alberta", note: "Owned by Suncor Energy, TSX/NYSE: SU. Suncor considered selling the retail network in 2022 under investor pressure (Elliott Management) but decided to keep it. A 2024 report noted the CEO left the door open to reconsidering, but no sale has occurred as of this research. Worth re-checking periodically given that history.", confidence: "high",
    alternatives: [] },
  "circlek.ca": { brand: "Circle K", ownership: "Canada", hq: "Laval, Quebec", note: "Owned by Alimentation Couche-Tard, TSX: ATD — Canadian-headquartered global convenience store operator", confidence: "high",
    alternatives: [] },
  "7-eleven.ca": { brand: "7-Eleven", ownership: "not-US", hq: "Tokyo, Japan (parent)", note: "Not US-owned — parent is Seven & i Holdings, a Japanese company. Not Canadian either.", confidence: "high",
    alternatives: ["Circle K", "Petro-Canada", "Couche-Tard-owned stores"] },
  "esso.ca": { brand: "Esso", ownership: "US", hq: "Irving, Texas", note: "Owned by Exxon Mobil (Imperial Oil is the Canadian operating subsidiary, but Exxon Mobil holds a majority stake), NYSE: XOM", confidence: "high",
    alternatives: ["Petro-Canada", "Circle K"] },
  "shell.ca": { brand: "Shell", ownership: "not-US", hq: "London, UK", note: "Not US-owned — UK-headquartered (Shell plc). Not Canadian either.", confidence: "high",
    alternatives: ["Petro-Canada", "Circle K"] },
  "intactfinancial.com": { brand: "Intact Insurance", ownership: "Canada", hq: "Toronto, Ontario", note: "TSX: IFC — largest property and casualty insurer in Canada", confidence: "high",
    alternatives: [] },
  "cooperators.ca": { brand: "Co-operators", ownership: "Canada", hq: "Guelph, Ontario", note: "Canadian-owned cooperative insurance and financial services group", confidence: "high",
    alternatives: [] },
  "allstate.ca": { brand: "Allstate Canada", ownership: "US", hq: "Northbrook, Illinois", note: "Subsidiary of The Allstate Corporation, NYSE: ALL", confidence: "high",
    alternatives: ["Intact Insurance", "Co-operators", "Desjardins Insurance"] },
  "jeancoutu.com": { brand: "Jean Coutu", ownership: "Canada", hq: "Longueuil, Quebec", note: "Acquired by Metro Inc. in 2018, TSX: MRU", confidence: "high",
    alternatives: [] },
  "pharmasave.com": { brand: "Pharmasave", ownership: "Canada", hq: "Vancouver, BC", note: "Member-owned Canadian pharmacy cooperative/franchise", confidence: "high",
    alternatives: [] },
  "herschel.com": { brand: "Herschel Supply Co.", ownership: "Canada", hq: "Vancouver, BC", note: "Founded 2009 by Lyndon and Jamie Cormack, privately held", confidence: "high",
    alternatives: [] },
  "tilley.com": { brand: "Tilley", ownership: "Canada", hq: "Don Mills, Ontario", note: "Privately held Canadian outdoor apparel brand", confidence: "high",
    alternatives: [] },
  "mackage.com": { brand: "Mackage", ownership: "verify", hq: "Montreal, Quebec", note: "Sources conflict on current ownership: Wikipedia states Mackage is owned by APP Group Inc. (the Elfassy family's Canadian leather company), but an M&A database (Mergr) states it is owned by Lee Equity Partners, a US private equity firm. Genuinely unresolved with the sources available — needs a direct check (e.g. the company's own investor/about page or a recent news report) before this is asserted either way.", confidence: "verify",
    alternatives: [] },
  "frankandoak.com": { brand: "Frank And Oak", ownership: "US", hq: "Montreal, Quebec (operations) / New York, New York (Unified Commerce Group)", note: "Canadian-founded (Montreal, 2012) but acquired out of bankruptcy protection by Unified Commerce Group, a New York-based retail acquisition firm, in October 2020. Stores and operations remain Canadian-facing, but ownership is US. Confirmed via multiple independent business press reports on the 2020 acquisition and UCG's own statements.", confidence: "high",
    alternatives: ["Kotn (Canadian)", "Naked & Famous Denim (Canadian)"] },
  "reitmans.com": { brand: "Reitmans", ownership: "Canada", hq: "Montreal, Quebec", note: "TSX: RET.A — Canadian women's clothing retailer since 1926", confidence: "high",
    alternatives: [] },
  "harrys.com": { brand: "Harry Rosen", ownership: "Canada", hq: "Toronto, Ontario", note: "Privately held, family-owned Canadian menswear retailer since 1954. Larry Rosen (son of founder Harry Rosen) actively leads the company; celebrated 70 years family-run in 2024 with no indication of a sale. Confirmed via multiple independent business press profiles.", confidence: "high",
    alternatives: [] },
  "simons.ca": { brand: "Simons", ownership: "Canada", hq: "Quebec City, Quebec", note: "Privately held, family-owned Canadian department store since 1840", confidence: "high",
    alternatives: [] },
  "hbc.com": { brand: "Hudson's Bay", ownership: "verify", hq: "Toronto, Ontario", note: "Genuinely complicated: HBC filed for CCAA bankruptcy protection in March 2025 and liquidated nearly all its 355-year-old store network by June 2025. Confirmed via multiple independent news sources (Retail Insider, CTV, The Conversation). Current status of the brand/IP post-liquidation needs a fresh check before this entry is used for anything.", confidence: "verify",
    alternatives: [] },
  "freedommobile.ca": { brand: "Freedom Mobile", ownership: "Canada", hq: "Toronto, Ontario", note: "Owned by Videotron (a Quebecor subsidiary) since April 2023, after being owned by Shaw 2016–2023. Confirmed via Quebecor/Shaw joint announcement and Canadian government (ISED) regulatory filing.", confidence: "high",
    alternatives: [] },
  "fido.ca": { brand: "Fido", ownership: "Canada", hq: "Toronto, Ontario", note: "Owned by Rogers Communications, TSX: RCI.B", confidence: "high",
    alternatives: [] },
  "koodomobile.com": { brand: "Koodo", ownership: "Canada", hq: "Vancouver, BC", note: "Owned by Telus, TSX: T", confidence: "high",
    alternatives: [] },
  "virginplus.ca": { brand: "Virgin Plus", ownership: "Canada", hq: "Toronto, Ontario", note: "Owned by Bell (BCE Inc.) — 'Virgin' is a licensed brand name only, not UK/Virgin Group ownership", confidence: "high",
    alternatives: [] },
  "publicmobile.ca": { brand: "Public Mobile", ownership: "Canada", hq: "Toronto, Ontario", note: "Owned by Telus, TSX: T", confidence: "high",
    alternatives: [] },
  "chatrmobile.com": { brand: "Chatr Mobile", ownership: "Canada", hq: "Toronto, Ontario", note: "Owned by Rogers Communications, TSX: RCI.B", confidence: "high",
    alternatives: [] },
  "nbc.ca": { brand: "National Bank of Canada", ownership: "Canada", hq: "Montreal, Quebec", note: "TSX: NA", confidence: "high",
    alternatives: [] },
  "sleepcountry.ca": { brand: "Sleep Country Canada", ownership: "Canada", hq: "Brampton, Ontario", note: "TSX: ZZZ", confidence: "high",
    alternatives: [] },
  "leons.ca": { brand: "Leon's Furniture", ownership: "Canada", hq: "Toronto, Ontario", note: "TSX: LNF", confidence: "high",
    alternatives: [] },
  "thebrick.com": { brand: "The Brick", ownership: "Canada", hq: "Edmonton, Alberta", note: "Owned by Leon's Furniture, TSX: LNF, since 2013", confidence: "high",
    alternatives: [] },
  "structube.com": { brand: "Structube", ownership: "Canada", hq: "Montreal, Quebec", note: "Privately held Canadian furniture retailer", confidence: "high",
    alternatives: [] },
  "eq3.com": { brand: "EQ3", ownership: "Canada", hq: "Winnipeg, Manitoba", note: "Owned by Palliser Furniture, a privately held Canadian company", confidence: "high",
    alternatives: [] },
  "partycity.ca": { brand: "Party City Canada", ownership: "Canada", hq: "Toronto, Ontario", note: "Canadian retail business and stores acquired by Canadian Tire Corporation in 2019 for $174.4M — the brand name is US in origin but the Canadian retail operation itself is Canadian Tire-owned. Confirmed via CTC's own announcement and multiple independent business press reports.", confidence: "high",
    alternatives: [] },
  "michaels.com": { brand: "Michaels", ownership: "US", hq: "Irving, Texas", note: "Owned by Apollo Global Management, a US private equity firm", confidence: "high",
    alternatives: ["DeSerres (Canadian craft retailer)"] },
  "gap.com": { brand: "Gap / Old Navy / Banana Republic", ownership: "US", hq: "San Francisco, California", note: "Gap Inc., NYSE: GAP", confidence: "high",
    alternatives: ["Aritzia", "Roots"] },
  "sephora.com": { brand: "Sephora", ownership: "not-US", hq: "Paris, France", note: "Owned by LVMH — French, not US-owned. Not Canadian either.", confidence: "high",
    alternatives: [] },
  "hm.com": { brand: "H&M", ownership: "not-US", hq: "Stockholm, Sweden", note: "Not US-owned — Swedish company. Not Canadian either.", confidence: "high",
    alternatives: [] },
  "zara.com": { brand: "Zara", ownership: "not-US", hq: "Arteixo, Spain", note: "Owned by Inditex — Spanish, not US-owned. Not Canadian either.", confidence: "high",
    alternatives: [] },
  "aldoshoes.com": { brand: "Aldo", ownership: "Canada", hq: "Montreal, Quebec", note: "Privately held Canadian footwear and accessories retailer", confidence: "high",
    alternatives: [] },
  "kijiji.ca": { brand: "Kijiji", ownership: "not-US", hq: "Toronto, Ontario (Canadian operations) / owned by Adevinta, Norway", note: "Not US-owned — Adevinta is a Norwegian global classifieds company (Oslo-listed). Not Canadian-owned either, despite the Canadian operational HQ.", confidence: "high",
    alternatives: ["Facebook Marketplace is also not Canadian (US/Meta) — no major Canadian-owned classifieds alternative at this scale"] },
  "airtransat.com": { brand: "Air Transat", ownership: "Canada", hq: "Montreal, Quebec", note: "Owned by Transat A.T. Inc., TSX: TRZ. Air Canada's proposed 2019 acquisition was terminated by mutual agreement in April 2021 after EU regulators indicated they would not approve it — Transat remains independent and Canadian. Confirmed via Air Canada's own press release.", confidence: "high",
    alternatives: [] },
  "sunwing.ca": { brand: "Sunwing", ownership: "Canada", hq: "Toronto, Ontario", note: "Acquired by WestJet (itself owned by Onex Corporation, a Canadian PE firm) in May 2023. Previously majority-owned by the Hunter family (51%) with TUI Group (Germany) holding 49% — that structure was superseded by the WestJet acquisition. Confirmed via multiple independent news reports.", confidence: "high",
    alternatives: [] },
  "autotrader.ca": { brand: "AutoTrader.ca", ownership: "verify", hq: "Toronto, Ontario (operations)", note: "Genuinely unclear: formerly Canadian-owned TRADER Corporation, acquired by AutoScout24 (a German company) which itself has US private equity backing (Thoma Bravo was involved in the deal per company press releases). The exact current ownership chain needs a dedicated check before this is used confidently either way.", confidence: "verify",
    alternatives: [] },
  "canadacomputers.com": { brand: "Canada Computers & Electronics", ownership: "Canada", hq: "Markham, Ontario", note: "Privately held Canadian electronics retailer", confidence: "high",
    alternatives: [] },
  "memoryexpress.com": { brand: "Memory Express", ownership: "Canada", hq: "Burnaby, BC", note: "Privately held Canadian electronics retailer", confidence: "high",
    alternatives: [] },
  "endy.com": { brand: "Endy", ownership: "Canada", hq: "Toronto, Ontario", note: "Owned by Sleep Country Canada Holdings, TSX: ZZZ, since 2018", confidence: "high",
    alternatives: [] },
  "casper.com": { brand: "Casper", ownership: "US", hq: "New York, New York", note: "Taken private by Durational Capital Management (US) in 2022. Note: Casper's Canadian retail operations and assets were separately acquired by Sleep Country Canada — the Canadian business specifically is now Canadian-owned even though the global Casper brand/US parent is not.", confidence: "high",
    alternatives: ["Endy (also Sleep Country-owned)"] },
  "booking.com": { brand: "Booking.com", ownership: "US", hq: "Norwalk, Connecticut", note: "Owned by Booking Holdings (formerly Priceline), NASDAQ: BKNG", confidence: "high",
    alternatives: [] },
  "tripadvisor.ca": { brand: "TripAdvisor", ownership: "US", hq: "Needham, Massachusetts", note: "NASDAQ: TRIP", confidence: "high",
    alternatives: [] },
  "fairmont.com": { brand: "Fairmont Hotels", ownership: "not-US", hq: "Paris, France (Accor)", note: "Genuinely interesting history: originally Canadian (Canadian Pacific Hotels acquired majority interest in 1999), but the Fairmont brand was later sold and is now owned by Accor, a French hospitality group — not US-owned, and no longer Canadian-owned either despite the brand's Canadian roots and many landmark Canadian properties (Banff Springs, Château Frontenac).", confidence: "high",
    alternatives: [] },

  // ---- Everyday household / personal care (small-ticket, high switching willingness) ----
  "tide.com": { brand: "Tide", ownership: "US", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: ["Nellie's (Canadian laundry powder)", "Attitude (Canadian, Quebec-based)"] },
  "dove.com": { brand: "Dove", ownership: "not-US", hq: "London, UK / Rotterdam, Netherlands", note: "Owned by Unilever — Anglo-Dutch, not US-owned. Not Canadian either.", confidence: "high",
    alternatives: ["Attitude (Canadian personal care)"] },
  "herbalessences.com": { brand: "Herbal Essences", ownership: "US", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: ["Attitude (Canadian natural haircare)", "Druide (Canadian, Quebec-based)"] },
  "nivea.ca": { brand: "Nivea", ownership: "not-US", hq: "Hamburg, Germany", note: "Owned by Beiersdorf AG — German, not US-owned. Not Canadian either.", confidence: "high",
    alternatives: ["Province Apothecary (Canadian skincare)"] },
  "thebodyshop.com": { brand: "The Body Shop", ownership: "not-US", hq: "Littlehampton, UK", note: "Not US-owned — UK-founded; ownership has changed hands several times (most recently a UK-based restructuring in 2024). Not Canadian either.", confidence: "verify",
    alternatives: ["Province Apothecary (Canadian skincare)"] },
  "attitudeliving.com": { brand: "Attitude", ownership: "Canada", hq: "Beloeil, Quebec", note: "Privately held Canadian personal care and household cleaning brand", confidence: "high",
    alternatives: [] },
  "nelliesclean.ca": { brand: "Nellie's", ownership: "Canada", hq: "Ontario", note: "Privately held Canadian natural laundry and cleaning brand", confidence: "high",
    alternatives: [] },
  "provinceapothecary.com": { brand: "Province Apothecary", ownership: "Canada", hq: "Toronto, Ontario", note: "Privately held Canadian natural skincare brand", confidence: "high",
    alternatives: [] },
  "kotn.com": { brand: "Kotn", ownership: "Canada", hq: "Toronto, Ontario", note: "Privately held Canadian ethical basics/clothing brand, founded 2015", confidence: "high",
    alternatives: [] },
  "nakedandfamous.com": { brand: "Naked & Famous Denim", ownership: "Canada", hq: "Montreal, Quebec", note: "Privately held Canadian denim brand — jeans cut, made, and sewn in Canada", confidence: "high",
    alternatives: [] },
  "peacecollective.com": { brand: "Peace Collective", ownership: "Canada", hq: "Toronto, Ontario", note: "Privately held Canadian clothing brand, founded 2014", confidence: "high",
    alternatives: [] },
  "kickinghorsecoffee.com": { brand: "Kicking Horse Coffee", ownership: "not-US", hq: "Invermere, BC (operations) / Turin, Italy (Lavazza Group)", note: "80% owned by Lavazza Group (Italy) since May 2017, purchased from Swander Pace Capital. Founder Elana Rosenfeld retains 20% and remains CEO. Not US-owned, but no longer majority Canadian-owned either — a common misconception given the strong Canadian brand identity. Confirmed via Lavazza's own 2017 acquisition announcement.", confidence: "high",
    alternatives: ["Ethical Bean Coffee (Canadian)", "Van Houtte (Canadian roots, now Keurig Dr Pepper-owned — verify before recommending)"] },
  "levis.com": { brand: "Levi's", ownership: "US", hq: "San Francisco, California", note: "Levi Strauss & Co., NYSE: LEVI", confidence: "high",
    alternatives: ["Naked & Famous Denim"] },
  "oldspice.com": { brand: "Old Spice", ownership: "US", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: ["Attitude (Canadian personal care)"] },
  "crest.com": { brand: "Crest", ownership: "US", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: [] },
  "colgate.com": { brand: "Colgate", ownership: "US", hq: "New York, New York", note: "Colgate-Palmolive, NYSE: CL", confidence: "high",
    alternatives: [] },
  "vanhoutte.com": { brand: "Van Houtte", ownership: "US", hq: "Montreal, Quebec (operations) / Burlington, Massachusetts (Keurig Dr Pepper)", note: "Despite very strong Canadian brand identity (founded Montreal 1919, marketed as an 'iconic Canadian brand'), Van Houtte has been owned by US-based Keurig Dr Pepper since 2010 (acquired by Green Mountain Coffee Roasters, which later merged into Keurig Dr Pepper). Confirmed via the original 2010 acquisition announcements and Keurig Canada's own press materials.", confidence: "high",
    alternatives: ["Kicking Horse Coffee (Lavazza/Italian-owned, not Canadian, but also not US)", "look for smaller independent Canadian roasters"] },
  "pantene.com": { brand: "Pantene", ownership: "US", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: ["Attitude (Canadian)", "Druide (Canadian)"] },
  "suave.com": { brand: "Suave", ownership: "not-US", hq: "London, UK / Rotterdam, Netherlands", note: "Owned by Unilever — Anglo-Dutch, not US-owned. Not Canadian either.", confidence: "high",
    alternatives: ["Attitude (Canadian)"] },
  "dawn-dish.com": { brand: "Dawn", ownership: "US", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: ["Attitude (Canadian dish soap)", "Bio-Vert (Canadian, Quebec-based)"] },
  "palmolive.com": { brand: "Palmolive", ownership: "US", hq: "New York, New York", note: "Colgate-Palmolive, NYSE: CL", confidence: "high",
    alternatives: ["Attitude (Canadian dish soap)"] },
  "pampers.com": { brand: "Pampers", ownership: "US", hq: "Cincinnati, Ohio", note: "Owned by Procter & Gamble, NYSE: PG", confidence: "high",
    alternatives: ["Royale (Irving Consumer Products, Canadian — launched diapers in 2024, self-described as 'the only Canadian manufacturer of diapers')"] },
  "huggies.com": { brand: "Huggies", ownership: "US", hq: "Irving, Texas", note: "Owned by Kimberly-Clark, NYSE: KMB", confidence: "high",
    alternatives: ["Royale (Irving Consumer Products, Canadian — launched diapers in 2024, self-described as 'the only Canadian manufacturer of diapers')"] },
  "royale.ca": { brand: "Royale", ownership: "Canada", hq: "Dieppe, New Brunswick", note: "Made by Irving Consumer Products, a privately held Canadian company (Irving family, New Brunswick). Royale has made tissue products for 60+ years and launched a diaper line in 2024. Confirmed via Irving Consumer Products' own press release, which specifically states Royale is 'the only Canadian manufacturer of diapers.'", confidence: "high",
    alternatives: [] },
  "presidentschoice.ca": { brand: "President's Choice", ownership: "Canada", hq: "Brampton, Ontario", note: "Owned by Loblaw Companies / George Weston Limited — Canada's largest private-label grocery brand", confidence: "high",
    alternatives: [] },
  "compliments.ca": { brand: "Compliments", ownership: "Canada", hq: "Stellarton, Nova Scotia", note: "Private-label brand owned by Sobeys / Empire Company Ltd.", confidence: "high",
    alternatives: [] },
  "lays.com": { brand: "Lay's / Doritos", ownership: "US", hq: "Purchase, New York", note: "Owned by PepsiCo (Frito-Lay division), NASDAQ: PEP", confidence: "high",
    alternatives: ["President's Choice or Compliments-brand chips (Canadian private label)"] },
  "kraftheinz.com": { brand: "Kraft Heinz", ownership: "US", hq: "Chicago, Illinois / Pittsburgh, Pennsylvania", note: "NASDAQ: KHC", confidence: "high",
    alternatives: ["President's Choice (Canadian private label)"] },
  "kelloggs.com": { brand: "Kellogg's", ownership: "US", hq: "Battle Creek, Michigan", note: "Now branded Kellanova after 2023 split, NYSE: K", confidence: "high",
    alternatives: ["President's Choice (Canadian private label)"] },
  "generalmills.com": { brand: "General Mills", ownership: "US", hq: "Minneapolis, Minnesota", note: "NYSE: GIS", confidence: "high",
    alternatives: ["President's Choice (Canadian private label)"] },

  // ---- News/media ----
  "nationalpost.com": { brand: "National Post / Financial Post", ownership: "US", hq: "Toronto, Ontario (operations) / Chatham Borough, New Jersey (Chatham Asset Management)", note: "Owned by Postmedia Network, which is 63-66% owned by Chatham Asset Management, an American hedge fund — despite widespread perception as a purely Canadian newspaper chain. Confirmed via Postmedia's own SEDAR/TSX disclosures and multiple independent news reports (Globe and Mail, Wikipedia citing primary sources).", confidence: "high",
    alternatives: ["The Globe and Mail (Canadian, Woodbridge/Thomson family-owned)", "CBC News"] },
  "theglobeandmail.com": { brand: "The Globe and Mail", ownership: "Canada", hq: "Toronto, Ontario", note: "Owned by The Woodbridge Company (Thomson family), a privately held Canadian company", confidence: "high",
    alternatives: [] },
  "globalnews.ca": { brand: "Global News", ownership: "Canada", hq: "Toronto, Ontario", note: "Owned by Corus Entertainment, TSX: CJR.B — controlled by the Shaw family", confidence: "high",
    alternatives: [] },
  "ctvnews.ca": { brand: "CTV News", ownership: "Canada", hq: "Toronto, Ontario", note: "Owned by Bell Media (BCE Inc.), TSX: BCE", confidence: "high",
    alternatives: [] },

  // ---- Gaming platforms ----
  "store.steampowered.com": { brand: "Steam", ownership: "US", hq: "Bellevue, Washington", note: "Owned by Valve Corporation, privately held US company", confidence: "high",
    alternatives: [] },
  "epicgames.com": { brand: "Epic Games Store", ownership: "US", hq: "Cary, North Carolina", note: "Epic Games, privately held US company", confidence: "high",
    alternatives: [] },
  "playstation.com": { brand: "PlayStation Store", ownership: "not-US", hq: "Tokyo, Japan", note: "Owned by Sony Group Corporation — Japanese, not US-owned. Not Canadian either.", confidence: "high",
    alternatives: [] },
  "xbox.com": { brand: "Xbox / Microsoft Store", ownership: "US", hq: "Redmond, Washington", note: "Owned by Microsoft, NASDAQ: MSFT", confidence: "high",
    alternatives: [] },
  "nintendo.com": { brand: "Nintendo eShop", ownership: "not-US", hq: "Kyoto, Japan", note: "Not US-owned — Japanese company. Not Canadian either.", confidence: "high",
    alternatives: [] },
  "ea.com": { brand: "Electronic Arts (EA)", ownership: "US", hq: "Redwood City, California", note: "NASDAQ: EA. Note: EA owns BioWare, originally a Canadian studio (Edmonton, founded 1995) — the studio still operates in Edmonton but the parent company is US.", confidence: "high",
    alternatives: [] },
  "ubisoft.com": { brand: "Ubisoft", ownership: "not-US", hq: "Saint-Mandé, France", note: "Not US-owned — French company. Not Canadian either. Note: Ubisoft has major Canadian studios (Montreal, Toronto, Quebec City) but the parent company is French.", confidence: "high",
    alternatives: [] },
  "twitch.tv": { brand: "Twitch", ownership: "US", hq: "San Francisco, California", note: "Owned by Amazon, NASDAQ: AMZN", confidence: "high",
    alternatives: [] },
  "discord.com": { brand: "Discord", ownership: "US", hq: "San Francisco, California", note: "Privately held US company", confidence: "high",
    alternatives: [] },
  "roblox.com": { brand: "Roblox", ownership: "US", hq: "San Mateo, California", note: "NYSE: RBLX", confidence: "high",
    alternatives: [] },

  // ---- Reference / high-traffic utility sites ----
  "wikipedia.org": { brand: "Wikipedia", ownership: "US", hq: "San Francisco, California", note: "Operated by the Wikimedia Foundation, a US-based nonprofit — not a for-profit company, but legally US-domiciled. Not Canadian.", confidence: "high",
    alternatives: [] },
  "indeed.com": { brand: "Indeed", ownership: "not-US", hq: "Austin, Texas (US operations) / Tokyo, Japan (Recruit Holdings)", note: "Owned by Recruit Holdings, a Japanese company — not US-owned despite the US operational headquarters. Not Canadian either.", confidence: "high",
    alternatives: [] },
  "linkedin.com": { brand: "LinkedIn", ownership: "US", hq: "Sunnyvale, California", note: "Owned by Microsoft, NASDAQ: MSFT", confidence: "high",
    alternatives: [] },

  // ---- eLearning / instructional design services ----
  "sweetrush.com": { brand: "SweetRush", ownership: "US", hq: "San Francisco, California", note: "Privately held US custom eLearning and instructional design agency", confidence: "high",
    alternatives: ["The Learning Designers (Canadian custom eLearning/instructional design agency)"] },
  "thelearningdesigners.ca": { brand: "The Learning Designers", ownership: "Canada", hq: "Canada", note: "The Learning Designers Incorporated — a custom eLearning design and development / instructional design agency. Confirmed 100% Canadian owned and operated directly by a contractor who works with the company and knows the owner personally — a stronger source than a public registry lookup would be for a small private company.", confidence: "high",
    alternatives: [] },
};

// Simple lookup by hostname
function lookupDomain(hostname) {
  const clean = hostname.replace(/^www\./, "");
  return OWNERSHIP_DATA[clean] || null;
}
